/**
 * @deprecated Phase 6 — MCP tools are now implemented natively in ToolRegistry
 * (worker.ts). Agent containers use their own mcp.json configs generated by
 * scripts/generate-agent-config.js. This mapper is no longer used in any
 * active execution path. Scheduled for removal.
 *
 * MCP Configuration Mapper
 *
 * Maps an agent's enabled_tools list to MCP server configurations.
 * Tools that map to native Claude Code capabilities (file_ops, shell_exec, etc.)
 * are skipped — they don't need MCP servers.
 */

// ============================================
// Types
// ============================================

export interface McpServerConfig {
  /** MCP server URL (SSE endpoint) */
  url: string;
  /** Tools provided by this server */
  tools: string[];
}

export interface McpConfig {
  servers: McpServerConfig[];
  /** Tools that are handled natively by Claude Code (no MCP needed) */
  nativeTools: string[];
  /** Tools that had no MCP mapping (unknown) */
  unmappedTools: string[];
}

// ============================================
// Tool → MCP Server Mapping
// ============================================

/** MCP server URLs (internal Docker network) */
const MCP_WORKFLOW_URL = process.env['MCP_WORKFLOW_URL'] ?? 'http://mcp-workflow:3010';
const MCP_DATA_URL = process.env['MCP_DATA_URL'] ?? 'http://mcp-data:3011';
const MCP_INFRA_URL = process.env['MCP_INFRA_URL'] ?? 'http://mcp-infra:3012';

/** Map of tool name → MCP server URL */
const TOOL_TO_SERVER: Record<string, string> = {
  // mcp-workflow (port 3010)
  ticket_ops: MCP_WORKFLOW_URL,
  finding_ops: MCP_WORKFLOW_URL,
  intervention_ops: MCP_WORKFLOW_URL,
  agent_call: MCP_WORKFLOW_URL,

  // mcp-data (port 3011)
  db_query: MCP_DATA_URL,
  substrate_db_query: MCP_DATA_URL,
  memory_search: MCP_DATA_URL,
  memory_store: MCP_DATA_URL,

  // mcp-infra (port 3012)
  docker_api: MCP_INFRA_URL,
  deploy_ops: MCP_INFRA_URL,
  security_scan: MCP_INFRA_URL,
  code_analysis: MCP_INFRA_URL,
};

/** Tools handled natively by Claude Code (no MCP needed) */
const NATIVE_TOOLS = new Set([
  'file_ops',      // → Claude Code Read/Write/Edit
  'shell_exec',    // → Claude Code Bash
  'web_browse',    // → Claude Code WebFetch
  'web_search',    // → Claude Code WebSearch (or SearXNG MCP)
  'code_exec',     // → Claude Code Bash (node/python)
  'git_ops',       // → Claude Code Bash (git natively)
  'api_call',      // → Claude Code Bash (curl) or WebFetch
]);

// ============================================
// Configuration Builder
// ============================================

/**
 * Build MCP configuration from an agent's enabled tools list.
 *
 * Groups tools by their MCP server, skips native tools,
 * and reports any unmapped tools.
 */
export function buildMcpConfig(enabledTools: string[]): McpConfig {
  const serverMap = new Map<string, string[]>();
  const nativeTools: string[] = [];
  const unmappedTools: string[] = [];

  for (const tool of enabledTools) {
    if (NATIVE_TOOLS.has(tool)) {
      nativeTools.push(tool);
      continue;
    }

    const serverUrl = TOOL_TO_SERVER[tool];
    if (serverUrl) {
      const existing = serverMap.get(serverUrl) ?? [];
      existing.push(tool);
      serverMap.set(serverUrl, existing);
    } else {
      unmappedTools.push(tool);
    }
  }

  const servers: McpServerConfig[] = [];
  for (const [url, tools] of serverMap) {
    servers.push({ url, tools });
  }

  return { servers, nativeTools, unmappedTools };
}

/**
 * Build Claude Code CLI --mcp-config JSON for a set of MCP servers.
 * This is the format expected by `claude --mcp-config`.
 */
export function buildClaudeCodeMcpJson(config: McpConfig): Record<string, unknown> {
  const mcpServers: Record<string, { type: string; url: string }> = {};

  for (const server of config.servers) {
    // Use a human-readable name based on the URL
    let name = 'mcp-server';
    if (server.url.includes('workflow')) name = 'workflow';
    else if (server.url.includes('data')) name = 'data';
    else if (server.url.includes('infra')) name = 'infra';

    mcpServers[name] = { type: 'http', url: `${server.url}/mcp` };
  }

  return { mcpServers };
}
