#!/usr/bin/env node

/**
 * create-askalf
 *
 * Interactive CLI to set up and run AskAlf without Docker.
 *
 * Usage:
 *   npx create-askalf           # interactive setup
 *   npx create-askalf --quick   # skip prompts, use defaults
 */

import prompts from 'prompts';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { execSync, spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';

const BANNER = `
  ╔═══════════════════════════════════════════╗
  ║              create-askalf                ║
  ║                                           ║
  ║   The first self-healing AI workforce.    ║
  ║   No Docker. No Postgres. No Redis.       ║
  ║   Just Node.js.                           ║
  ╚═══════════════════════════════════════════╝
`;

const REPO_URL = 'https://github.com/askalf/askalf.git';

function defaultDataDir(): string {
  if (process.platform === 'win32') {
    return join(process.env['APPDATA'] || join(homedir(), 'AppData', 'Roaming'), 'askalf');
  }
  return join(homedir(), '.askalf');
}

function generateSecret(bytes = 32): string {
  return randomBytes(bytes).toString('hex');
}

function hasCommand(cmd: string): boolean {
  try {
    execSync(process.platform === 'win32' ? `where ${cmd}` : `which ${cmd}`, { stdio: 'pipe' });
    return true;
  } catch { return false; }
}

function installPnpm(): boolean {
  console.log('  Installing pnpm...');
  try {
    execSync('npm install -g pnpm', { stdio: 'pipe' });
    return true;
  } catch {
    try {
      execSync('corepack enable && corepack prepare pnpm@latest --activate', { stdio: 'pipe' });
      return true;
    } catch { return false; }
  }
}

async function main() {
  console.log(BANNER);

  // Check prerequisites
  if (!hasCommand('git')) {
    console.log('  ✗ git is required but not installed.');
    console.log('    Install: https://git-scm.com/downloads');
    process.exit(1);
  }
  if (!hasCommand('node')) {
    console.log('  ✗ Node.js is required but not installed.');
    console.log('    Install: https://nodejs.org');
    process.exit(1);
  }
  console.log('  ✓ git found');
  console.log('  ✓ Node.js ' + process.version);

  // Auto-install pnpm if missing
  if (!hasCommand('pnpm')) {
    if (!installPnpm()) {
      console.log('  ✗ pnpm is required but could not be installed.');
      console.log('    Install manually: npm install -g pnpm');
      process.exit(1);
    }
  }
  console.log('  ✓ pnpm found');
  console.log('');

  const quick = process.argv.includes('--quick');

  let answers: Record<string, any>;

  if (quick) {
    answers = {
      dataDir: defaultDataDir(),
      port: 3000,
      anthropicKey: process.env['ANTHROPIC_API_KEY'] || '',
      openaiKey: process.env['OPENAI_API_KEY'] || '',
      adminEmail: 'admin@localhost',
    };
  } else {
    answers = await prompts([
      {
        type: 'text',
        name: 'dataDir',
        message: 'Where should AskAlf store data?',
        initial: defaultDataDir(),
      },
      {
        type: 'number',
        name: 'port',
        message: 'Port to run on?',
        initial: 3000,
      },
      {
        type: 'password',
        name: 'anthropicKey',
        message: 'Anthropic API key (sk-ant-...):',
        initial: process.env['ANTHROPIC_API_KEY'] || '',
      },
      {
        type: 'password',
        name: 'openaiKey',
        message: 'OpenAI API key (optional):',
        initial: process.env['OPENAI_API_KEY'] || '',
      },
      {
        type: 'text',
        name: 'adminEmail',
        message: 'Admin email:',
        initial: 'admin@localhost',
      },
    ]);
  }

  if (!answers.dataDir) {
    console.log('Aborted.');
    process.exit(0);
  }

  const dataDir = answers.dataDir as string;

  // Create directories
  console.log('\n  Creating data directory...');
  for (const sub of ['', 'data', 'data/pglite', 'logs', 'config']) {
    const dir = join(dataDir, sub);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  }

  // Generate .env
  const envPath = join(dataDir, '.env');
  if (!existsSync(envPath)) {
    console.log('  Generating configuration...');
    const env = [
      `# AskAlf Standalone Configuration`,
      `# Generated by create-askalf`,
      ``,
      `ASKALF_MODE=standalone`,
      `ASKALF_DATA_DIR=${dataDir}`,
      `PORT=${answers.port}`,
      ``,
      `# AI Providers (at least one required)`,
      `ANTHROPIC_API_KEY=${answers.anthropicKey || ''}`,
      `OPENAI_API_KEY=${answers.openaiKey || ''}`,
      ``,
      `# Admin`,
      `ADMIN_EMAIL=${answers.adminEmail}`,
      `ADMIN_PASSWORD=${generateSecret(16)}`,
      ``,
      `# Security (auto-generated)`,
      `JWT_SECRET=${generateSecret()}`,
      `SESSION_SECRET=${generateSecret()}`,
      `FORGE_API_KEY=fk_${generateSecret(24)}`,
      `CHANNEL_ENCRYPTION_KEY=${generateSecret()}`,
      `INTERNAL_API_SECRET=${generateSecret()}`,
      ``,
    ].join('\n');

    writeFileSync(envPath, env);
    console.log(`  Config saved to ${envPath}`);
  } else {
    console.log(`  Using existing config at ${envPath}`);
  }

  // Clone or update AskAlf
  const installDir = join(dataDir, 'askalf');
  // Check if we have a valid install
  const hasValidInstall = existsSync(join(installDir, 'package.json'));

  if (!hasValidInstall) {
    // Clean stale dir if it exists
    if (existsSync(installDir)) {
      try {
        const { rmSync } = await import('node:fs');
        rmSync(installDir, { recursive: true, force: true });
      } catch {
        // Windows lock — clone into a fresh name instead
        const fallback = installDir + '-' + Date.now();
        console.log('\n  Downloading AskAlf...');
        execSync(`git clone --depth 1 ${REPO_URL} "${fallback}"`, { stdio: 'inherit' });
        // Swap dirs
        try {
          const { renameSync } = await import('node:fs');
          renameSync(installDir, installDir + '-old');
          renameSync(fallback, installDir);
        } catch {
          // If rename fails too, just use the fallback
          console.log(`  Using ${fallback}`);
        }
      }
    }
    if (!existsSync(join(installDir, 'package.json'))) {
      console.log('\n  Downloading AskAlf...');
      try {
        execSync(`git clone --depth 1 ${REPO_URL} "${installDir}"`, { stdio: 'inherit' });
      } catch {
        console.log('  ✗ Could not download AskAlf. Check your internet connection.');
        process.exit(1);
      }
    }
  } else {
    console.log('\n  Updating AskAlf...');
    try {
      execSync('git pull --ff-only', { cwd: installDir, stdio: 'pipe' });
      console.log('  Updated to latest.');
    } catch {
      console.log('  Using existing version.');
    }
  }

  // Install dependencies with pnpm (npm can't handle workspace: protocol)
  console.log('\n  Installing dependencies...');
  try {
    execSync('pnpm install --frozen-lockfile', { cwd: installDir, stdio: 'inherit' });
  } catch {
    try {
      execSync('pnpm install', { cwd: installDir, stdio: 'inherit' });
    } catch {
      console.log('  ✗ Dependency install failed.');
      console.log(`    Try manually: cd "${installDir}" && pnpm install`);
      process.exit(1);
    }
  }

  // Build everything needed
  console.log('\n  Building...');
  const buildSteps = [
    'pnpm --filter @askalf/core build',
    'pnpm --filter @askalf/database-adapter build',
    'pnpm --filter @askalf/redis-adapter build',
    'pnpm --filter @askalf/db build',
    'pnpm --filter @askalf/observability build',
    'pnpm --filter @askalf/email build',
    'pnpm --filter @askalf/database build',
    'pnpm --filter @askalf/auth build',
    'pnpm --filter @askalf/forge build',
    'pnpm --filter @askalf/standalone build',
  ];
  for (const step of buildSteps) {
    try {
      execSync(step, { cwd: installDir, stdio: 'pipe' });
      const pkg = step.match(/@askalf\/([^\s]+)/)?.[1] || step;
      console.log(`  ✓ ${pkg}`);
    } catch {
      const pkg = step.match(/@askalf\/([^\s]+)/)?.[1] || step;
      console.log(`  ~ ${pkg} (skipped)`);
    }
  }

  // Start
  console.log('\n  Starting AskAlf...\n');

  const env: Record<string, string> = { ...process.env as Record<string, string> };
  const envContent = readFileSync(envPath, 'utf-8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
  }

  const child = spawn('node', [join('apps', 'standalone', 'dist', 'index.js')], {
    cwd: installDir,
    env,
    stdio: 'inherit',
    shell: true,
  });

  child.on('error', (err) => {
    // Fallback to tsx if dist doesn't exist
    console.log('  Trying with tsx...');
    const fallback = spawn('npx', ['tsx', join('apps', 'standalone', 'src', 'index.ts')], {
      cwd: installDir,
      env,
      stdio: 'inherit',
      shell: true,
    });
    fallback.on('error', () => {
      console.error('  ✗ Failed to start AskAlf:', err.message);
      process.exit(1);
    });
    fallback.on('exit', (code) => process.exit(code ?? 0));
  });

  child.on('exit', (code) => {
    process.exit(code ?? 0);
  });
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
