-- WAVE 3 BATCH 7: More science, math, definitions, geography, history (60 shards)

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-photosynthesis-equation',
  1,
  'function execute(input) { return "The photosynthesis equation is:\n\n6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂\n\nIn words: six molecules of carbon dioxide + six molecules of water + sunlight → one molecule of glucose + six molecules of oxygen.\n\nPlants absorb CO₂ from air and water from soil, use sunlight (captured by chlorophyll) as energy, and produce glucose (food/energy) and oxygen (released into the air). It''s essentially the reverse of cellular respiration and is the foundation of nearly all life on Earth."; }',
  '["photosynthesis equation", "photosynthesis formula", "chemical equation.*photosynthesis", "equation for photosynthesis"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Photosynthesis equation',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-speed-of-sound',
  1,
  'function execute(input) { return "The speed of sound in dry air at 20°C (68°F) is approximately 343 meters per second (1,125 feet per second, or 767 mph). It varies with temperature, humidity, and the medium:\n\n• In air at 0°C: 331 m/s\n• In water: ~1,480 m/s (about 4.3x faster)\n• In steel: ~5,960 m/s (about 17x faster)\n\nSound travels faster in denser materials because molecules are closer together. Mach 1 equals the speed of sound. When an object exceeds Mach 1, it creates a sonic boom. The speed of sound is much slower than light (300,000 km/s), which is why you see lightning before hearing thunder."; }',
  '["speed of sound.*air", "how fast.*sound travel", "speed of sound.*water", "mach 1.*speed", "sound.*meters per second"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Speed of sound details',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-ph-scale',
  1,
  'function execute(input) { return "The pH scale measures how acidic or basic (alkaline) a substance is, ranging from 0 to 14:\n\n• pH 0-6: Acidic (more hydrogen ions)\n• pH 7: Neutral (pure water)\n• pH 8-14: Basic/alkaline (fewer hydrogen ions)\n\nCommon examples:\n• Battery acid: pH 0\n• Lemon juice: pH 2\n• Vinegar: pH 2.5\n• Coffee: pH 5\n• Pure water: pH 7\n• Baking soda: pH 9\n• Bleach: pH 12.5\n\nThe scale is logarithmic — each whole number represents a 10x difference. pH 4 is 10 times more acidic than pH 5."; }',
  '["what is.*ph scale", "ph scale", "explain ph", "ph meaning", "acidic.*basic.*scale"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the pH scale',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-isotope',
  1,
  'function execute(input) { return "An isotope is a variant of a chemical element that has the same number of protons but a different number of neutrons. This gives them the same atomic number but different atomic masses. For example, carbon has three isotopes: Carbon-12 (6 protons, 6 neutrons — the most common), Carbon-13 (6 protons, 7 neutrons), and Carbon-14 (6 protons, 8 neutrons — radioactive, used in carbon dating). Some isotopes are stable, others are radioactive (unstable) and decay over time. Radioactive isotopes are used in medicine (imaging, cancer treatment), archaeology (dating), and energy (nuclear power)."; }',
  '["what is an isotope", "isotope meaning", "define isotope", "explain isotope", "isotope examples"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an isotope',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-richter-scale',
  1,
  'function execute(input) { return "The Richter scale (more accurately, the moment magnitude scale used today) measures earthquake magnitude on a logarithmic scale. Each whole number increase represents roughly 32 times more energy released:\n\n• 2.0-2.9: Micro — not felt\n• 3.0-3.9: Minor — often felt, rarely causes damage\n• 4.0-4.9: Light — noticeable shaking, minor damage\n• 5.0-5.9: Moderate — can cause significant damage to weak buildings\n• 6.0-6.9: Strong — destructive in populated areas\n• 7.0-7.9: Major — serious damage over large areas\n• 8.0+: Great — devastating over vast areas\n\nThe largest recorded earthquake was 9.5 in Chile (1960)."; }',
  '["richter scale", "earthquake scale", "what is the richter", "earthquake magnitude", "how.*earthquake.*measured"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Richter scale',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-dark-matter',
  1,
  'function execute(input) { return "Dark matter is a mysterious substance that makes up about 27% of the universe but doesn''t emit, absorb, or reflect light — making it invisible. We know it exists because of its gravitational effects: galaxies rotate faster than they should based on visible matter, and light bends around invisible mass (gravitational lensing). Dark matter holds galaxies together — without it, galaxies would fly apart. Normal matter (atoms, stars, planets, you) makes up only about 5% of the universe. Dark energy (68%) is even more mysterious, driving the universe''s accelerating expansion. Neither has been directly detected."; }',
  '["what is dark matter", "dark matter meaning", "explain dark matter", "dark matter.*dark energy", "what.*dark matter made of"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is dark matter',
  'space',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-doppler-effect',
  1,
  'function execute(input) { return "The Doppler effect is the change in frequency of a wave as the source and observer move relative to each other. The classic example: an ambulance siren sounds higher-pitched as it approaches and lower-pitched as it moves away. This happens because sound waves are compressed (shorter wavelength, higher pitch) when the source moves toward you and stretched (longer wavelength, lower pitch) when moving away. The Doppler effect also applies to light — astronomers use \"redshift\" (light stretched to longer wavelengths) to measure how fast distant galaxies are moving away from us."; }',
  '["doppler effect", "what is the doppler", "doppler.*explained", "explain doppler", "why.*siren.*pitch"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Doppler effect',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-absolute-zero',
  1,
  'function execute(input) { return "Absolute zero is the lowest theoretically possible temperature: 0 Kelvin, -273.15°C, or -459.67°F. At absolute zero, atoms would have minimum possible motion (though quantum mechanics says they''d still have some \"zero-point energy\"). It can never actually be reached — only approached. Scientists have cooled matter to within billionths of a degree above absolute zero. At near-absolute-zero temperatures, exotic states of matter emerge, like Bose-Einstein condensates. The concept is fundamental to thermodynamics and the Kelvin temperature scale."; }',
  '["what is absolute zero", "absolute zero.*temperature", "coldest.*temperature.*possible", "0 kelvin", "absolute zero meaning"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is absolute zero',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-derivative-math',
  1,
  'function execute(input) { return "In calculus, a derivative measures the rate of change of a function — how fast the output changes as the input changes. Geometrically, it''s the slope of the tangent line to a curve at a given point. If f(x) represents position over time, the derivative f''(x) represents velocity (how fast position changes). The notation is f''(x) or dy/dx. Example: if f(x) = x², then f''(x) = 2x. At x = 3, the slope is 6 — the function is changing at rate 6 at that point. Derivatives are foundational to physics, engineering, economics, and machine learning."; }',
  '["what is a derivative.*math", "derivative.*calculus", "derivative meaning.*math", "explain derivative", "how.*derivative.*work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a derivative',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-standard-deviation',
  1,
  'function execute(input) { return "Standard deviation (SD or σ) is a measure of how spread out numbers are from the average (mean). A low SD means data points are close to the mean; a high SD means they''re spread far from the mean. In a normal distribution:\n\n• 68% of data falls within 1 SD of the mean\n• 95% within 2 SDs\n• 99.7% within 3 SDs\n\nExample: if test scores have mean 75 and SD 10, most students scored between 65-85. If SD were 5, most scored between 70-80 (more tightly clustered). It''s one of the most important concepts in statistics."; }',
  '["what is standard deviation", "standard deviation meaning", "explain standard deviation", "standard deviation.*statistics"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is standard deviation',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-probability',
  1,
  'function execute(input) { return "Probability is the measure of how likely an event is to occur, expressed as a number between 0 (impossible) and 1 (certain), or as a percentage (0-100%). The basic formula is: P(event) = favorable outcomes ÷ total possible outcomes. Examples:\n\n• Coin flip (heads): 1/2 = 50%\n• Rolling a 6 on a die: 1/6 ≈ 16.7%\n• Drawing an ace from a deck: 4/52 ≈ 7.7%\n\nKey concepts: independent events (coin flips don''t affect each other), mutually exclusive events (can''t happen simultaneously), and conditional probability (probability given that something else happened)."; }',
  '["what is probability", "probability meaning", "explain probability", "how.*calculate probability", "probability formula"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is probability',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-exponent',
  1,
  'function execute(input) { return "An exponent tells you how many times to multiply a number by itself. In 2³, the base is 2 and the exponent is 3, meaning 2 × 2 × 2 = 8. Key rules:\n\n• x⁰ = 1 (anything to the power of 0 is 1)\n• x¹ = x\n• x⁻ⁿ = 1/xⁿ (negative exponent = reciprocal)\n• xᵃ × xᵇ = xᵃ⁺ᵇ (multiply = add exponents)\n• xᵃ ÷ xᵇ = xᵃ⁻ᵇ (divide = subtract exponents)\n• (xᵃ)ᵇ = xᵃˣᵇ (power of power = multiply exponents)\n\nExponents are also called powers or indices. Fractional exponents represent roots: x^(1/2) = √x."; }',
  '["what is an exponent", "exponent meaning", "exponent rules", "how.*exponents work", "power.*math"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an exponent',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-prime-number',
  1,
  'function execute(input) { return "A prime number is a natural number greater than 1 that can only be divided evenly by 1 and itself. The first 20 primes are: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71.\n\nKey facts:\n• 2 is the only even prime number\n• 1 is NOT a prime number\n• There are infinitely many primes (proved by Euclid)\n• Every number can be expressed as a product of primes (fundamental theorem of arithmetic)\n\nPrime numbers are essential to modern cryptography — RSA encryption relies on the difficulty of factoring large numbers into their prime components."; }',
  '["what is a prime number", "prime number meaning", "prime numbers", "list.*prime numbers", "explain prime numbers"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a prime number',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-order-of-operations',
  1,
  'function execute(input) { return "The order of operations (PEMDAS/BODMAS) defines the sequence for evaluating math expressions:\n\n1. Parentheses / Brackets\n2. Exponents / Orders (powers, roots)\n3. Multiplication and Division (left to right)\n4. Addition and Subtraction (left to right)\n\nNote: Multiplication and Division have EQUAL priority (done left to right), as do Addition and Subtraction.\n\nExample: 8 + 2 × 5 = 8 + 10 = 18 (not 50)\nExample: 3 + 6 × (5 + 4) ÷ 3 - 7 = 3 + 6 × 9 ÷ 3 - 7 = 3 + 18 - 7 = 14\n\nMemory aid: Please Excuse My Dear Aunt Sally."; }',
  '["order of operations", "pemdas", "bodmas", "math.*order.*operations", "pemdas.*meaning"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Order of operations',
  'math',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-australia',
  1,
  'function execute(input) { return "The capital of Australia is Canberra, not Sydney or Melbourne as many assume. Canberra was purpose-built as a compromise when Sydney and Melbourne couldn''t agree on which should be the capital. It was designed by American architects Walter Burley Griffin and Marion Mahony Griffin, and became the capital in 1927. Canberra is located in the Australian Capital Territory (ACT), about 280 km from Sydney and 660 km from Melbourne. Its population is about 460,000."; }',
  '["capital of australia", "australia.*capital", "what is.*capital.*australia"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Australia',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-canada',
  1,
  'function execute(input) { return "The capital of Canada is Ottawa, Ontario — not Toronto or Montreal as commonly assumed. Ottawa was chosen as the capital by Queen Victoria in 1857, partly because it was on the border between English-speaking Ontario and French-speaking Quebec, and partly because it was farther from the US border than Toronto (more defensible). Ottawa has a population of about 1 million (metro area ~1.5 million). It''s home to Parliament Hill, the National Gallery, and the Rideau Canal (a UNESCO World Heritage Site)."; }',
  '["capital of canada", "canada.*capital", "what is.*capital.*canada"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Canada',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-brazil',
  1,
  'function execute(input) { return "The capital of Brazil is Brasília, not São Paulo or Rio de Janeiro. Brasília was purpose-built as a new capital and inaugurated on April 21, 1960, replacing Rio de Janeiro. It was designed by urban planner Lúcio Costa and architect Oscar Niemeyer in a modernist style. From above, the city''s layout resembles an airplane or bird. Brasília is a UNESCO World Heritage Site and has a population of about 3 million. It was built in the country''s interior to promote development of Brazil''s central regions."; }',
  '["capital of brazil", "brazil.*capital", "what is.*capital.*brazil"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Brazil',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-japan',
  1,
  'function execute(input) { return "The capital of Japan is Tokyo, the most populous metropolitan area in the world with about 37 million people in the greater metro area. Tokyo became the capital in 1868 when Emperor Meiji moved the imperial seat from Kyoto. The name Tokyo means \"Eastern Capital.\" It''s the center of Japan''s government, economy, and culture, housing the Imperial Palace, Tokyo Tower, and Shibuya Crossing. Despite its massive size, Tokyo is known for its safety, cleanliness, punctual trains, and blend of ultra-modern technology with traditional culture."; }',
  '["capital of japan", "japan.*capital", "what is.*capital.*japan"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Japan',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-india',
  1,
  'function execute(input) { return "The capital of India is New Delhi, a district within the larger city of Delhi. New Delhi was designed by British architects Edwin Lutyens and Herbert Baker and inaugurated in 1931, replacing Calcutta (now Kolkata) as the capital of British India. Delhi''s metro area is one of the world''s most populated with about 32 million people. New Delhi houses India''s Parliament, the Presidential Palace (Rashtrapati Bhavan), and India Gate. While Mumbai is India''s financial capital, New Delhi is the political and administrative center."; }',
  '["capital of india", "india.*capital", "what is.*capital.*india"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of India',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-great-wall-of-china',
  1,
  'function execute(input) { return "The Great Wall of China is a series of fortifications built across northern China to protect against invasions. Total length of all sections is about 21,196 km (13,171 miles), though the most famous and well-preserved sections are from the Ming Dynasty (1368-1644). Construction began as early as the 7th century BC. It''s NOT visible from space with the naked eye (a common myth). The wall varies from 5-8 meters high and 4.5-8 meters wide. It''s a UNESCO World Heritage Site and one of the New Seven Wonders of the World."; }',
  '["great wall of china", "how long.*great wall", "great wall.*facts", "tell me about.*great wall", "when.*great wall.*built"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Great Wall of China facts',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'who-was-alexander-the-great',
  1,
  'function execute(input) { return "Alexander the Great (356-323 BC) was a king of Macedon who created one of the largest empires in ancient history by age 30. Tutored by Aristotle as a youth, he became king at 20 after his father Philip II was assassinated. He conquered the Persian Empire, Egypt (founding Alexandria), and parts of Central Asia and India — never losing a battle. His empire stretched from Greece to northwestern India. He died at 32 in Babylon, possibly from typhoid fever, poisoning, or excessive drinking. His conquests spread Greek culture across the known world (Hellenistic period)."; }',
  '["who was alexander the great", "alexander the great", "tell me about alexander.*great", "alexander.*macedon"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Who was Alexander the Great',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-constitution',
  1,
  'function execute(input) { return "The US Constitution is the supreme law of the United States, ratified in 1788. It establishes the framework of the federal government with three branches: Legislative (Congress — makes laws), Executive (President — enforces laws), and Judicial (Supreme Court — interprets laws). This separation of powers includes checks and balances so no branch becomes too powerful. The Constitution has been amended 27 times. The first 10 amendments are the Bill of Rights (freedom of speech, religion, press, right to bear arms, etc.). It''s the oldest written national constitution still in use."; }',
  '["what is the constitution", "us constitution", "american constitution", "constitution meaning", "explain.*constitution"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the US Constitution',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-analogy',
  1,
  'function execute(input) { return "An analogy is a comparison between two things that are alike in some way, used to explain or clarify a concept. Unlike a metaphor (which says something IS something else), an analogy extends the comparison to show HOW they''re similar.\n\nExamples:\n• \"A CPU is to a computer what a brain is to the body\"\n• \"Writing code without testing is like building a bridge without inspecting the materials\"\n• \"Electrons orbit the nucleus like planets orbit the Sun\"\n\nAnalogies are powerful learning tools because they connect unfamiliar concepts to familiar ones. They''re widely used in teaching, writing, SAT tests, and everyday explanations."; }',
  '["what is an analogy", "analogy meaning", "define analogy", "analogy examples", "explain analogy"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an analogy',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-irony',
  1,
  'function execute(input) { return "Irony is when reality differs from what''s expected, often in a humorous or poignant way. Three main types:\n\n• Verbal irony: Saying the opposite of what you mean (sarcasm is a form of this). \"Oh great, another flat tire.\"\n\n• Situational irony: When the outcome is the opposite of what''s expected. A fire station burning down. A marriage counselor getting divorced.\n\n• Dramatic irony: When the audience knows something the characters don''t. In Romeo and Juliet, the audience knows Juliet isn''t really dead.\n\nCommon mistake: Rain on your wedding day is unfortunate, not ironic (unless you''re a meteorologist who predicted sunshine)."; }',
  '["what is irony", "irony meaning", "types of irony", "define irony", "irony examples", "explain irony"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is irony',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-simile',
  1,
  'function execute(input) { return "A simile is a figure of speech that compares two unlike things using \"like\" or \"as.\" Examples:\n\n• \"Brave as a lion\"\n• \"Her smile was like sunshine\"\n• \"He runs like the wind\"\n• \"Life is like a box of chocolates\" (Forrest Gump)\n• \"Cool as a cucumber\"\n• \"Busy as a bee\"\n\nThe key difference from a metaphor: a simile uses \"like\" or \"as\" (She is LIKE a rose), while a metaphor states it directly (She IS a rose). Similes make descriptions more vivid and help readers visualize abstract qualities."; }',
  '["what is a simile", "simile meaning", "define simile", "simile examples", "simile vs metaphor"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a simile',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-haiku',
  1,
  'function execute(input) { return "A haiku is a traditional Japanese poem with a strict syllable structure:\n\n• Line 1: 5 syllables\n• Line 2: 7 syllables\n• Line 3: 5 syllables\n\nTotal: 17 syllables in 3 lines.\n\nTraditional haiku focus on nature and include a seasonal reference (kireji). Example by Matsuo Bashō:\n\n\"An old silent pond / A frog jumps into the pond / Splash! Silence again.\"\n\nModern haiku in English are more flexible with syllable counts but retain the brief, evocative style capturing a single moment or image. Haiku originated in the 17th century from the opening verse of collaborative linked poems."; }',
  '["what is a haiku", "haiku meaning", "haiku.*syllable", "haiku format", "how.*write.*haiku"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a haiku',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-sonnet',
  1,
  'function execute(input) { return "A sonnet is a 14-line poem with a specific rhyme scheme and meter. The two main types:\n\n• Shakespearean (English): Three quatrains + a couplet. Rhyme: ABAB CDCD EFEF GG. Written in iambic pentameter (10 syllables per line, alternating unstressed/stressed). The final couplet often delivers a twist or resolution.\n\n• Petrarchan (Italian): An octave (8 lines, ABBAABBA) + a sestet (6 lines, various schemes). A \"volta\" (turn) between them shifts the argument.\n\nShakespeare wrote 154 sonnets. Famous first line: \"Shall I compare thee to a summer''s day?\" (Sonnet 18)."; }',
  '["what is a sonnet", "sonnet meaning", "sonnet.*syllables", "sonnet format", "sonnet.*rhyme scheme"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a sonnet',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-ethereum',
  1,
  'function execute(input) { return "Ethereum is a decentralized blockchain platform created by Vitalik Buterin, launched in 2015. While Bitcoin is primarily digital money, Ethereum is a programmable blockchain that supports smart contracts — self-executing code that runs when conditions are met. Its cryptocurrency is called Ether (ETH). Key features:\n\n• Smart contracts enable decentralized applications (dApps)\n• It powers DeFi (decentralized finance), NFTs, and DAOs\n• Switched from Proof of Work to Proof of Stake in 2022 (\"The Merge\"), reducing energy use by ~99.95%\n• ETH is the second-largest cryptocurrency by market cap after Bitcoin"; }',
  '["what is ethereum", "ethereum meaning", "explain ethereum", "ethereum vs bitcoin", "what is eth"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is Ethereum',
  'technology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-5g',
  1,
  'function execute(input) { return "5G is the fifth generation of mobile network technology, succeeding 4G/LTE. Key improvements:\n\n• Speed: Up to 10 Gbps (10-100x faster than 4G)\n• Latency: 1-10ms response time (vs 30-50ms for 4G)\n• Capacity: Can connect 1 million devices per square kilometer\n\n5G uses three frequency bands: low-band (wide coverage, moderate speed), mid-band (balanced), and mmWave (extremely fast but short range). It enables autonomous vehicles, remote surgery, IoT, and enhanced AR/VR. Rollout began in 2019 and is still expanding globally. It does NOT cause health issues — this is a debunked conspiracy theory."; }',
  '["what is 5g", "5g meaning", "explain 5g", "5g.*speed", "how.*5g work", "5g vs 4g"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is 5G',
  'technology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-black-swan-event',
  1,
  'function execute(input) { return "A Black Swan event is an extremely rare, unpredictable event with massive consequences that people rationalize in hindsight as if it were predictable. The term was popularized by Nassim Nicholas Taleb in his 2007 book \"The Black Swan.\" Three characteristics: 1) It''s an outlier — nothing in the past pointed to its possibility, 2) It has extreme impact, 3) After it occurs, people construct explanations making it seem predictable. Examples: 9/11, the 2008 financial crisis, COVID-19, and the rise of the internet. The name comes from the assumption that all swans were white — until black swans were discovered in Australia."; }',
  '["black swan.*event", "what is a black swan", "black swan meaning", "explain black swan", "nassim taleb.*black swan"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a Black Swan event',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-paradox',
  1,
  'function execute(input) { return "A paradox is a statement or situation that seems contradictory or absurd but may actually be true, or reveals a deeper truth. Famous paradoxes:\n\n• The Ship of Theseus: If you replace every part of a ship, is it still the same ship?\n• The Grandfather Paradox: If you traveled back in time and prevented your grandfather from meeting your grandmother, would you exist?\n• Zeno''s Paradox: To reach a wall, you must first go halfway, then half of that, infinitely — so motion is impossible (yet we move).\n• The Liar''s Paradox: \"This statement is false\" — if true, it''s false; if false, it''s true.\n\nParadoxes have driven advances in philosophy, math, and physics."; }',
  '["what is a paradox", "paradox meaning", "famous paradox", "paradox examples", "explain paradox"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a paradox',
  'definitions',
  0
);
