-- WAVE 3 BATCH 9: Final 50 to hit 500

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-meme',
  1,
  'function execute(input) { return "A meme (rhymes with \"cream\") has two meanings. Originally coined by Richard Dawkins in The Selfish Gene (1976), a meme is a cultural unit of information that spreads from person to person — ideas, behaviors, catchphrases, or styles. In internet culture, a meme is a humorous image, video, or text that is copied and spread rapidly online, often with variations. Internet memes evolve quickly, have short lifespans, and reflect current culture. Examples: Doge, Distracted Boyfriend, Drake hotline bling. The study of memes is called memetics."; }',
  '["what is a meme", "meme meaning", "where.*meme.*come from", "meme.*origin", "define meme"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a meme',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-hypothesis',
  1,
  'function execute(input) { return "A hypothesis is a testable, proposed explanation for an observation or phenomenon. It''s an educated guess based on existing knowledge that can be supported or refuted through experimentation. A good hypothesis is: specific, testable, falsifiable (can be proven wrong), and based on observation.\n\nExample: \"Plants watered with sugar water will grow taller than plants watered with plain water.\"\n\nA hypothesis differs from a theory — a hypothesis is a single testable prediction, while a theory is a well-substantiated explanation supported by extensive evidence (like the theory of evolution or theory of relativity). Hypotheses are the starting point of the scientific method."; }',
  '["what is a hypothesis", "hypothesis meaning", "define hypothesis", "hypothesis vs theory", "hypothesis.*example"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a hypothesis',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-weather-climate',
  1,
  'function execute(input) { return "Weather and climate are related but different:\n\n• Weather: Short-term atmospheric conditions at a specific place and time. Changes hourly/daily. \"It''s raining today.\" Includes temperature, humidity, wind, precipitation, and cloud cover.\n\n• Climate: Long-term average of weather patterns in a region, typically measured over 30+ years. \"Seattle is rainy.\" Describes what conditions are TYPICAL for an area.\n\nSimple way to remember: Climate is what you EXPECT, weather is what you GET. Or: \"Climate is your wardrobe, weather is what you wear today.\"\n\nClimate change refers to long-term shifts in global temperature and weather patterns, not individual weather events."; }',
  '["weather vs climate", "difference.*weather.*climate", "weather.*climate.*difference", "climate vs weather"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Weather vs climate',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-eclipse',
  1,
  'function execute(input) { return "An eclipse occurs when one celestial body moves into the shadow of another. Two types:\n\n• Solar eclipse: The Moon passes between Earth and the Sun, blocking sunlight. Total eclipses (Moon fully covers the Sun) are rare at any given location — maybe once every 375 years. The next total solar eclipse visible from the US is August 23, 2044.\n\n• Lunar eclipse: Earth passes between the Sun and Moon, casting its shadow on the Moon. The Moon often turns red (\"Blood Moon\") because Earth''s atmosphere bends red light onto it. Lunar eclipses are visible from anywhere on Earth''s night side.\n\nSolar eclipses last minutes; lunar eclipses can last hours. NEVER look directly at a solar eclipse without proper eclipse glasses."; }',
  '["what is an eclipse", "eclipse meaning", "solar eclipse", "lunar eclipse", "eclipse.*explained"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an eclipse',
  'space',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-neuron',
  1,
  'function execute(input) { return "A neuron is a nerve cell — the basic unit of the nervous system that transmits information through electrical and chemical signals. The human brain has approximately 86 billion neurons. Structure:\n\n• Cell body (soma): Contains the nucleus\n• Dendrites: Branch-like extensions that receive signals from other neurons\n• Axon: Long projection that carries signals away from the cell body\n• Synapse: Gap between neurons where chemical neurotransmitters transmit signals\n\nNeurons communicate via action potentials (electrical impulses) traveling up to 120 m/s. Types include sensory neurons (detect stimuli), motor neurons (control muscles), and interneurons (process information). Neural networks in AI are loosely inspired by biological neurons."; }',
  '["what is a neuron", "neuron meaning", "how.*neuron.*work", "neuron.*explained", "nerve cell"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a neuron',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-prism',
  1,
  'function execute(input) { return "A prism is a transparent optical element with flat, polished surfaces that refract (bend) light. The most familiar type is a triangular glass prism that separates white light into a rainbow spectrum (the colors of visible light). This works because different wavelengths of light bend at slightly different angles — violet bends most, red least. Isaac Newton famously used a prism in 1666 to demonstrate that white light is a mixture of all colors. Prisms are used in binoculars, cameras, periscopes, and spectrometers. The Pink Floyd album \"The Dark Side of the Moon\" features the iconic prism and spectrum image."; }',
  '["what is a prism", "prism meaning", "how.*prism.*work", "prism.*rainbow", "prism.*light"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a prism',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-allergy',
  1,
  'function execute(input) { return "An allergy is an overreaction of the immune system to a normally harmless substance (allergen). When exposed, the immune system produces antibodies (IgE) that trigger the release of histamine and other chemicals, causing symptoms. Common allergens: pollen, dust mites, pet dander, certain foods (nuts, shellfish, eggs), insect stings, medications, and latex.\n\nSymptoms range from mild (sneezing, itching, hives) to severe (anaphylaxis — a life-threatening reaction requiring immediate epinephrine). About 30% of adults and 40% of children have allergies. They''re treated with antihistamines, decongestants, immunotherapy (allergy shots), and allergen avoidance. Allergies can develop at any age."; }',
  '["what is an allergy", "allergy meaning", "how.*allergies work", "allergy.*explained", "what causes allergies"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an allergy',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-semiconductor',
  1,
  'function execute(input) { return "A semiconductor is a material with electrical conductivity between a conductor (copper) and an insulator (glass). Silicon is the most common semiconductor. What makes them special: their conductivity can be precisely controlled by adding impurities (doping) and applying voltage. This allows them to act as switches and amplifiers — the foundation of all modern electronics.\n\nSemiconductors are used to make transistors, which are the building blocks of computer chips. A modern CPU contains billions of transistors. The semiconductor industry is dominated by TSMC (Taiwan), Samsung, and Intel. The global chip shortage (2020-2023) highlighted how dependent modern technology is on semiconductors."; }',
  '["what is a semiconductor", "semiconductor meaning", "semiconductor.*explained", "how.*semiconductor.*work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a semiconductor',
  'technology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-ocean-sea',
  1,
  'function execute(input) { return "The main differences between an ocean and a sea:\n\n• Size: Oceans are much larger. The smallest ocean (Arctic, 14 million km²) is larger than the largest sea (Philippine Sea, 5.7 million km²).\n\n• Location: Oceans are open bodies of water between continents. Seas are smaller and usually partially enclosed by land.\n\n• Depth: Oceans are generally deeper. The deepest ocean point (Mariana Trench) is ~11,000 meters.\n\nThere are 5 oceans: Pacific, Atlantic, Indian, Southern, Arctic.\nExamples of seas: Mediterranean, Caribbean, Red Sea, South China Sea, Black Sea.\n\nAll seas are connected to oceans. The terms are sometimes used interchangeably in casual speech."; }',
  '["ocean vs sea", "difference.*ocean.*sea", "sea vs ocean", "ocean.*sea.*difference"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Ocean vs sea',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-rna',
  1,
  'function execute(input) { return "RNA (Ribonucleic Acid) is a molecule essential for gene expression — it carries instructions from DNA to make proteins. Key differences from DNA:\n\n• RNA is usually single-stranded; DNA is double-stranded\n• RNA uses uracil (U); DNA uses thymine (T)\n• RNA uses ribose sugar; DNA uses deoxyribose\n\nMain types:\n• mRNA (messenger): Carries genetic code from DNA to ribosomes\n• tRNA (transfer): Brings amino acids to ribosomes during protein synthesis\n• rRNA (ribosomal): Forms part of the ribosome structure\n\nRNA is central to the \"central dogma\" of biology: DNA → RNA → Protein. mRNA vaccines (COVID-19) work by giving cells mRNA instructions to produce a viral protein and trigger immunity."; }',
  '["what is rna", "rna meaning", "rna vs dna", "types of rna", "rna.*explained"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is RNA',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-food-chain',
  1,
  'function execute(input) { return "A food chain shows the transfer of energy from one organism to another through eating. It starts with producers (plants) and moves through consumers:\n\n1. Producers: Plants/algae that make their own food via photosynthesis\n2. Primary consumers: Herbivores that eat plants (rabbits, deer, caterpillars)\n3. Secondary consumers: Carnivores that eat herbivores (foxes, frogs)\n4. Tertiary consumers: Top predators (eagles, sharks, lions)\n5. Decomposers: Break down dead organisms (fungi, bacteria)\n\nExample: Grass → Rabbit → Fox → Eagle\n\nEnergy is lost at each level (~90%), which is why there are fewer top predators than prey animals. A food web is multiple interconnected food chains in an ecosystem."; }',
  '["what is a food chain", "food chain meaning", "food chain.*explained", "food chain.*examples", "food chain vs food web"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a food chain',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-osmosis',
  1,
  'function execute(input) { return "Osmosis is the movement of water molecules through a semipermeable membrane from an area of lower solute concentration to higher solute concentration. In simpler terms: water moves to balance out concentrations on both sides of a membrane. The membrane lets water through but blocks larger dissolved molecules.\n\nExamples:\n• Plant roots absorb water from soil through osmosis\n• Your kidneys use osmosis to filter blood\n• Placing a raisin in water causes it to swell (water moves into the raisin)\n• Salting a slug draws water out of its body through osmosis\n\nReverse osmosis (forcing water through a membrane to remove contaminants) is used for water purification and desalination."; }',
  '["what is osmosis", "osmosis meaning", "osmosis.*explained", "how.*osmosis work", "define osmosis"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is osmosis',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-constitution-general',
  1,
  'function execute(input) { return "A constitution is the fundamental set of principles and rules by which a country, state, or organization is governed. It typically:\n\n• Establishes the structure of government\n• Defines the powers and limits of each branch\n• Protects individual rights and freedoms\n• Sets out how laws are made and changed\n\nConstitutions can be written (a single document, like the US Constitution) or unwritten (based on traditions, statutes, and court decisions, like the UK''s). Most countries have written constitutions. Changing a constitution usually requires a special process (supermajorities, referendums) to prevent casual modification of fundamental law."; }',
  '["what is a constitution", "constitution meaning", "define constitution", "constitution.*explained", "why.*constitution.*important"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a constitution (general)',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-amendment',
  1,
  'function execute(input) { return "An amendment is a formal change or addition to a legal document, most commonly a constitution. In the US, the Constitution has been amended 27 times. Notable amendments:\n\n• 1st: Freedom of speech, religion, press, assembly\n• 2nd: Right to bear arms\n• 4th: Protection against unreasonable search and seizure\n• 5th: Right against self-incrimination, due process\n• 13th: Abolished slavery (1865)\n• 14th: Equal protection under law (1868)\n• 15th: Voting rights regardless of race (1870)\n• 19th: Women''s right to vote (1920)\n• 21st: Repealed Prohibition (1933)\n\nAmending the US Constitution requires 2/3 of both houses of Congress and ratification by 3/4 of states."; }',
  '["what is an amendment", "amendment meaning", "constitutional amendment", "how many amendments", "bill of rights"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an amendment',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-alligator-crocodile',
  1,
  'function execute(input) { return "Alligators and crocodiles are both large reptiles but differ in several ways:\n\n• Snout shape: Alligators have a wide, U-shaped snout. Crocodiles have a narrow, V-shaped snout.\n• Teeth: When a crocodile''s mouth is closed, some lower teeth are visible (especially the 4th tooth). Alligator teeth are hidden when the mouth is closed.\n• Color: Alligators are darker (blackish). Crocodiles are lighter (olive/tan).\n• Habitat: Alligators prefer freshwater. Crocodiles tolerate saltwater (they have salt glands).\n• Location: Alligators are found in the US and China. Crocodiles live across the tropics worldwide.\n• Temperament: Crocodiles are generally more aggressive.\n• Size: Saltwater crocs can reach 20+ feet. American alligators max around 15 feet."; }',
  '["alligator vs crocodile", "difference.*alligator.*crocodile", "crocodile vs alligator", "alligator.*crocodile.*difference"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Alligator vs crocodile',
  'animals',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-frog-toad',
  1,
  'function execute(input) { return "Frogs and toads are both amphibians (order Anura), but they have key differences:\n\n• Skin: Frogs have smooth, moist skin. Toads have dry, bumpy/warty skin.\n• Body: Frogs are slender with long legs for jumping. Toads are stout with short legs for walking.\n• Habitat: Frogs live near water. Toads are more land-dwelling.\n• Eggs: Frogs lay eggs in clusters. Toads lay eggs in long chains.\n• Movement: Frogs jump. Toads walk or take short hops.\n\nScientifically, \"toad\" isn''t a strict classification — all toads are technically frogs, but not all frogs are toads. Toads belong to the family Bufonidae. Touching toads does NOT give you warts (a common myth)."; }',
  '["frog vs toad", "difference.*frog.*toad", "toad vs frog", "frog.*toad.*difference"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Frog vs toad',
  'animals',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-chromosomes-do-humans-have',
  1,
  'function execute(input) { return "Humans have 46 chromosomes, arranged in 23 pairs. Of these, 22 pairs are autosomes (non-sex chromosomes), and 1 pair are sex chromosomes (XX for female, XY for male). Each parent contributes 23 chromosomes through their egg or sperm cell. Chromosomes are made of tightly coiled DNA and carry our genes. Having too many or too few chromosomes can cause genetic conditions — Down syndrome, for example, is caused by an extra copy of chromosome 21 (trisomy 21, giving 47 chromosomes total). Other species have different numbers: dogs have 78, cats have 38, and bananas have 33."; }',
  '["how many chromosomes.*human", "chromosomes.*human", "human.*chromosomes", "how many chromosomes do we have", "46 chromosomes"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many chromosomes do humans have',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-blockchain',
  1,
  'function execute(input) { return "A blockchain is a distributed digital ledger that records transactions across many computers in a way that makes records nearly impossible to alter retroactively. Each \"block\" contains a batch of transactions, a timestamp, and a cryptographic hash of the previous block — forming a chain. Key features:\n\n• Decentralized: No single authority controls it\n• Immutable: Once recorded, data can''t be changed without altering all subsequent blocks\n• Transparent: All transactions are publicly verifiable\n• Consensus: Network participants must agree before new blocks are added\n\nBeyond cryptocurrency, blockchain is used for supply chain tracking, voting systems, smart contracts, digital identity, and NFTs. Major blockchains include Bitcoin, Ethereum, and Solana."; }',
  '["what is.*blockchain", "blockchain meaning", "blockchain.*explained", "how.*blockchain work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a blockchain (detailed)',
  'technology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-far-is-it-to-the-sun',
  1,
  'function execute(input) { return "The average distance from Earth to the Sun is about 93 million miles (150 million kilometers), a distance known as 1 Astronomical Unit (AU). This varies slightly because Earth''s orbit is elliptical:\n\n• Closest (perihelion): ~91.4 million miles (January)\n• Farthest (aphelion): ~94.5 million miles (July)\n\nLight from the Sun takes about 8 minutes 20 seconds to reach Earth. At highway speeds (60 mph), it would take about 177 years to drive to the Sun. At the speed of a commercial jet (~575 mph), about 18.4 years. The Sun contains 99.86% of all mass in our solar system."; }',
  '["how far.*earth.*sun", "distance.*earth.*sun", "how far is the sun", "miles.*sun", "sun.*distance"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How far is the Sun from Earth',
  'space',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-sustainable-energy',
  1,
  'function execute(input) { return "Sustainable (renewable) energy comes from sources that are naturally replenished and produce minimal greenhouse gas emissions. The main types:\n\n• Solar: Photovoltaic panels convert sunlight to electricity. Fastest-growing source.\n• Wind: Turbines convert wind to electricity. Onshore and offshore.\n• Hydroelectric: Dams convert flowing water to electricity. Largest renewable source.\n• Geothermal: Uses Earth''s internal heat. Reliable but location-dependent.\n• Biomass: Energy from organic materials (wood, crop waste, biogas).\n• Tidal/Wave: Harnesses ocean energy. Still emerging.\n\nRenewables now generate about 30% of global electricity and growing. Challenges include intermittency (sun doesn''t always shine), energy storage, and grid infrastructure upgrades."; }',
  '["sustainable energy", "renewable energy types", "types of renewable energy", "clean energy.*types", "green energy"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Types of sustainable energy',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-china',
  1,
  'function execute(input) { return "The capital of China is Beijing (formerly known as Peking). It has served as China''s capital for most of the last eight centuries. Beijing has a population of about 21.5 million people and is located in northern China. It''s home to the Forbidden City (imperial palace for 500 years), Tiananmen Square (one of the largest public squares in the world), the Temple of Heaven, and nearby sections of the Great Wall. Beijing hosted the Summer Olympics in 2008 and the Winter Olympics in 2022. While Shanghai is China''s largest city and financial hub, Beijing is the political and cultural center."; }',
  '["capital of china", "china.*capital", "what is.*capital.*china"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of China',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-germany',
  1,
  'function execute(input) { return "The capital of Germany is Berlin, the country''s largest city with about 3.7 million people (metro area ~6.1 million). Berlin was divided into East and West from 1961-1989 by the Berlin Wall during the Cold War. After reunification in 1990, Berlin became the capital of united Germany again (Bonn had been West Germany''s capital). It''s known for its history, vibrant arts scene, and landmarks including the Brandenburg Gate, Reichstag (parliament), Berlin Wall Memorial, and Checkpoint Charlie."; }',
  '["capital of germany", "germany.*capital", "what is.*capital.*germany"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Germany',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-france',
  1,
  'function execute(input) { return "The capital of France is Paris, known as the \"City of Light\" (La Ville Lumière). It''s France''s largest city with about 2.2 million in the city proper and 12.3 million in the metro area. Paris has been France''s capital since the late 10th century. Famous landmarks include the Eiffel Tower (1889), the Louvre Museum (world''s most visited), Notre-Dame Cathedral, the Arc de Triomphe, and the Champs-Élysées. Paris is a global center for art, fashion, gastronomy, and culture, and it hosted the Summer Olympics in 2024."; }',
  '["capital of france", "france.*capital", "what is.*capital.*france"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of France',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-russia',
  1,
  'function execute(input) { return "The capital of Russia is Moscow, the country''s largest city with about 13 million people (metro area ~21 million). Moscow is the political, economic, cultural, and scientific center of Russia. Key landmarks include the Kremlin (fortified complex housing the president''s residence), Red Square, St. Basil''s Cathedral, and the Bolshoi Theatre. Founded in 1147, Moscow has served as the capital of Russia for most of its history, except from 1712-1918 when Saint Petersburg was the capital (under the Russian Empire)."; }',
  '["capital of russia", "russia.*capital", "what is.*capital.*russia"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Russia',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-italy',
  1,
  'function execute(input) { return "The capital of Italy is Rome (Roma), often called the \"Eternal City.\" With about 2.8 million people, it''s Italy''s largest city. Rome was the center of the Roman Empire and has been continuously inhabited for over 2,800 years. Landmarks include the Colosseum, the Pantheon, the Roman Forum, the Trevi Fountain, and the Spanish Steps. Vatican City, an independent city-state and the seat of the Catholic Church, is entirely surrounded by Rome. Rome became Italy''s capital in 1871 after Italian unification."; }',
  '["capital of italy", "italy.*capital", "what is.*capital.*italy"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Italy',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-spain',
  1,
  'function execute(input) { return "The capital of Spain is Madrid, located in the center of the Iberian Peninsula. It''s Spain''s largest city with about 3.3 million people (metro ~6.8 million). Madrid became the capital in 1561 under King Philip II. It''s known for the Royal Palace, the Prado Museum (one of the world''s finest art museums), Retiro Park, and a vibrant nightlife culture. Madrid is also home to Real Madrid, one of the most successful football clubs in history. The city sits at 650 meters elevation, making it one of Europe''s highest capitals."; }',
  '["capital of spain", "spain.*capital", "what is.*capital.*spain"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Spain',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'capital-of-mexico',
  1,
  'function execute(input) { return "The capital of Mexico is Mexico City (Ciudad de México), the largest city in North America with about 9.2 million in the city and 21.8 million in the metro area. Built on the ruins of the Aztec capital Tenochtitlán (conquered by Hernán Cortés in 1521), it sits in the Valley of Mexico at 2,240 meters (7,350 feet) elevation. Notable sites include the Zócalo (one of the world''s largest public squares), the National Palace, Chapultepec Castle, and the Frida Kahlo Museum. Mexico City is sinking at a rate of about 50 cm per year due to groundwater extraction."; }',
  '["capital of mexico", "mexico.*capital", "what is.*capital.*mexico"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Capital of Mexico',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-simile-vs-metaphor',
  1,
  'function execute(input) { return "Similes and metaphors are both comparisons, but they work differently:\n\n• Simile: Uses \"like\" or \"as\" to compare. \"He is AS brave AS a lion.\" \"Life is LIKE a box of chocolates.\"\n\n• Metaphor: States one thing IS another directly. \"He IS a lion in battle.\" \"Life IS a box of chocolates.\"\n\nSimiles are gentler — they acknowledge the comparison. Metaphors are stronger — they claim identity. A third related device is personification (giving human qualities to non-human things): \"The wind whispered through the trees.\"\n\nEasy test: If it uses \"like\" or \"as\" for comparison, it''s a simile. If it makes a direct comparison without those words, it''s a metaphor."; }',
  '["simile vs metaphor", "difference.*simile.*metaphor", "metaphor vs simile", "simile.*metaphor.*difference"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Simile vs metaphor',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-photosynthesis-simple',
  1,
  'function execute(input) { return "Photosynthesis is the process by which plants (and some other organisms) convert sunlight, water, and carbon dioxide into glucose (sugar) and oxygen. In simple terms: plants eat sunlight and breathe out oxygen.\n\nThe process:\n1. Leaves absorb sunlight using chlorophyll (the green pigment)\n2. Roots absorb water from soil\n3. Leaves take in CO₂ from air through tiny pores (stomata)\n4. Using light energy, plants combine CO₂ and water to make glucose\n5. Oxygen is released as a byproduct\n\nPhotosynthesis is essential for life — it produces the oxygen we breathe and forms the base of virtually all food chains. Without it, most life on Earth couldn''t exist."; }',
  '["explain photosynthesis.*simple", "photosynthesis.*simple", "how.*photosynthesis.*work.*simple", "photosynthesis for kids", "easy.*explain.*photosynthesis"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Photosynthesis explained simply',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-gdpr',
  1,
  'function execute(input) { return "GDPR (General Data Protection Regulation) is a comprehensive data privacy law enacted by the European Union in 2018. It gives individuals control over their personal data and imposes obligations on organizations that collect or process it. Key rights:\n\n• Right to access your data\n• Right to be forgotten (data deletion)\n• Right to data portability\n• Right to be informed about data collection\n• Right to restrict processing\n\nOrganizations must: get explicit consent before collecting data, report data breaches within 72 hours, and appoint a Data Protection Officer if processing data at large scale. Violations can result in fines up to €20 million or 4% of global annual revenue. It applies to ANY organization handling EU residents'' data, regardless of location."; }',
  '["what is gdpr", "gdpr meaning", "gdpr.*explained", "general data protection", "gdpr.*rules"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is GDPR',
  'technology',
  0
);
