-- WAVE 3 BATCH 6: Health, Business, Conversions, Misc (50 shards)

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
-- ═══════════════════════════════════════════════════
-- HEALTH & BODY (15)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-teeth-do-adults-have',
  1,
  'function execute(input) { return "Adults have 32 teeth (including wisdom teeth): 8 incisors (front cutting teeth), 4 canines (pointed tearing teeth), 8 premolars (flat grinding teeth), and 12 molars (including 4 wisdom teeth). Many adults have 28 teeth if their wisdom teeth were removed. Children have 20 primary (baby) teeth that start falling out around age 6 and are gradually replaced by permanent teeth. Wisdom teeth typically emerge between ages 17-25."; }',
  '["how many teeth.*adult", "how many teeth.*human", "teeth.*adult.*how many", "number of teeth"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many teeth do adults have',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-blood-type',
  1,
  'function execute(input) { return "Blood type is determined by the presence or absence of antigens on red blood cells. The ABO system has four types: A, B, AB, and O. The Rh factor adds + or -, giving 8 common types: A+, A-, B+, B-, AB+, AB-, O+, O-.\n\n• O- is the universal donor (can give to anyone)\n• AB+ is the universal recipient (can receive from anyone)\n• O+ is the most common type (~37% of people)\n• AB- is the rarest (~0.6%)\n\nBlood type is inherited from parents and matters for transfusions and organ transplants."; }',
  '["what is.*blood type", "blood type", "blood types.*explain", "how many blood types", "what.*blood types.*there"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What are blood types',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-bmi',
  1,
  'function execute(input) { return "BMI (Body Mass Index) is a screening tool that estimates body fat based on height and weight. The formula is: BMI = weight (kg) ÷ height (m)². Categories:\n\n• Underweight: below 18.5\n• Normal: 18.5-24.9\n• Overweight: 25-29.9\n• Obese: 30+\n\nBMI is simple and widely used but has limitations — it doesn''t distinguish between muscle and fat, doesn''t account for body composition, age, sex, or ethnicity, and may miscategorize muscular athletes as overweight. It''s a screening tool, not a diagnostic measure."; }',
  '["what is bmi", "bmi meaning", "body mass index", "how.*calculate bmi", "bmi.*categories"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is BMI',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-melatonin',
  1,
  'function execute(input) { return "Melatonin is a hormone produced by the pineal gland in the brain that regulates your sleep-wake cycle (circadian rhythm). Production increases when it gets dark, making you sleepy, and decreases with light exposure. Factors that reduce melatonin: blue light from screens, bright lights at night, caffeine, and aging. Melatonin supplements are commonly used for jet lag, shift work, and insomnia. Typical supplement doses are 0.5-5mg taken 30-60 minutes before bed. It''s not a sedative — it signals to your body that it''s time to sleep."; }',
  '["what is melatonin", "melatonin meaning", "melatonin.*sleep", "how.*melatonin work", "explain melatonin"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is melatonin',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-organs-in-body',
  1,
  'function execute(input) { return "The human body has 78 organs, though the exact count depends on what you classify as an organ. The five vital organs (essential for survival) are: brain, heart, lungs, liver, and kidneys. Other major organs include the stomach, intestines, pancreas, spleen, skin (the largest organ by surface area), and the eyes. In 2018, scientists proposed the interstitium (a network of fluid-filled spaces in connective tissue) as a newly identified organ, bringing the traditional count to 79."; }',
  '["how many organs.*body", "organs in.*body", "how many organs.*human", "human body.*organs", "list.*organs"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many organs in the body',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-caffeine',
  1,
  'function execute(input) { return "Caffeine is a natural stimulant found in coffee, tea, chocolate, and many sodas and energy drinks. It works by blocking adenosine, a brain chemical that makes you feel tired. Effects include increased alertness, improved concentration, faster reaction times, and elevated mood. A typical cup of coffee has 80-100mg of caffeine. The FDA considers 400mg per day safe for most adults (about 4 cups of coffee). Caffeine''s half-life is 3-7 hours, meaning it takes that long for your body to eliminate half of it. It''s the world''s most widely consumed psychoactive substance."; }',
  '["what is caffeine", "caffeine meaning", "how.*caffeine work", "caffeine.*effects", "how much caffeine.*safe"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is caffeine',
  'health',
  0
),
-- ═══════════════════════════════════════════════════
-- BUSINESS & ECONOMICS (10)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-llc',
  1,
  'function execute(input) { return "An LLC (Limited Liability Company) is a business structure that combines the liability protection of a corporation with the tax flexibility of a partnership. Key features:\n\n• Personal assets are protected from business debts (limited liability)\n• Profits pass through to owners'' personal tax returns (no double taxation)\n• Flexible management structure\n• Fewer formalities than a corporation\n\nOwners are called \"members.\" An LLC can have one member (single-member LLC) or multiple. It''s one of the most popular business structures for small businesses in the US."; }',
  '["what is an llc", "llc meaning", "limited liability company", "explain llc", "what does llc stand for"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an LLC',
  'business',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-roi',
  1,
  'function execute(input) { return "ROI (Return on Investment) is a metric that measures the profitability of an investment. The formula is:\n\nROI = (Net Profit ÷ Cost of Investment) × 100\n\nExample: You invest $1,000 and earn $1,300 back. Net profit is $300. ROI = ($300 ÷ $1,000) × 100 = 30%.\n\nA positive ROI means you made money; negative means you lost money. ROI is used to compare investments, evaluate business decisions, and measure marketing effectiveness. Its limitation is that it doesn''t account for time — a 30% return in 1 year is better than 30% over 10 years."; }',
  '["what is roi", "roi meaning", "return on investment", "how.*calculate roi", "roi formula"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is ROI',
  'business',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-ipo',
  1,
  'function execute(input) { return "An IPO (Initial Public Offering) is when a private company sells shares to the public for the first time, becoming a publicly traded company on a stock exchange. The process: 1) Company hires investment banks as underwriters, 2) Files with the SEC (S-1 form), 3) Sets a price range, 4) Goes on a \"roadshow\" to attract investors, 5) Shares begin trading. Companies do IPOs to raise capital for growth, provide liquidity for early investors, and increase public visibility. Famous IPOs include Apple (1980), Google (2004), and Facebook (2012)."; }',
  '["what is an ipo", "ipo meaning", "initial public offering", "explain ipo", "how.*ipo work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an IPO',
  'business',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-startup',
  1,
  'function execute(input) { return "A startup is a newly established business, typically technology-driven, designed to scale rapidly. Key characteristics that distinguish startups from small businesses: 1) High growth potential, 2) Innovation-focused (new product, service, or business model), 3) Often venture-funded (angels, VCs), 4) High risk, high reward, 5) Focused on scalability. Common stages: idea → MVP (Minimum Viable Product) → seed funding → Series A/B/C → growth → exit (IPO or acquisition). About 90% of startups fail. The term is associated with Silicon Valley culture but applies globally."; }',
  '["what is a startup", "startup meaning", "define startup", "startup vs small business", "explain startup"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a startup',
  'business',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-supply-chain',
  1,
  'function execute(input) { return "A supply chain is the entire network of organizations, people, activities, and resources involved in creating and delivering a product from raw materials to the end customer. A typical supply chain includes: raw material suppliers → manufacturers → distributors → wholesalers → retailers → consumers. Modern supply chains are global and complex — a smartphone might have components from 40+ countries. Supply chain management focuses on efficiency, cost reduction, and resilience. The 2020-2022 disruptions (COVID, shipping delays) highlighted how vulnerable global supply chains can be."; }',
  '["what is.*supply chain", "supply chain meaning", "explain supply chain", "how.*supply chain work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a supply chain',
  'business',
  0
),
-- ═══════════════════════════════════════════════════
-- CONVERSIONS & MEASUREMENTS (12)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-milliliters-in-a-liter',
  1,
  'function execute(input) { return "There are 1,000 milliliters in 1 liter.\n\nMetric volume conversions:\n• 1 liter = 1,000 mL = 100 centiliters\n• 1 liter ≈ 33.81 US fluid ounces\n• 1 liter ≈ 4.23 US cups\n• 1 liter ≈ 0.264 US gallons\n• 1 mL = 1 cubic centimeter (cc)\n\nThe prefix \"milli-\" means one-thousandth. A standard water bottle is usually 500 mL (half a liter). A typical soda can is 355 mL (12 fl oz)."; }',
  '["how many milliliters in a liter", "ml.*liter", "liter.*ml", "milliliters.*liter"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many milliliters in a liter',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-milligrams-in-a-gram',
  1,
  'function execute(input) { return "There are 1,000 milligrams in 1 gram.\n\nMetric weight conversions:\n• 1 gram = 1,000 milligrams (mg)\n• 1 kilogram = 1,000 grams = 1,000,000 milligrams\n• 1 gram ≈ 0.035 ounces\n• 1 milligram = 0.001 grams = 1,000 micrograms (mcg/μg)\n\nContext: a paperclip weighs about 1 gram, a grain of salt weighs about 60 mg, and medication doses are often in milligrams (e.g., 200mg ibuprofen, 500mg acetaminophen)."; }',
  '["how many milligrams in a gram", "mg.*gram", "gram.*mg", "milligrams.*gram"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many milligrams in a gram',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-meters-in-a-kilometer',
  1,
  'function execute(input) { return "There are 1,000 meters in 1 kilometer.\n\nMetric distance conversions:\n• 1 kilometer = 1,000 meters = 100,000 centimeters\n• 1 kilometer ≈ 0.621 miles ≈ 3,281 feet\n• 1 mile ≈ 1.609 kilometers\n\nThe prefix \"kilo-\" means one thousand. A kilometer is about 62% of a mile. Quick mental conversion: multiply km by 0.6 for approximate miles, or multiply miles by 1.6 for approximate km. A 5K race is 5 kilometers = 3.1 miles. A 10K is 6.2 miles."; }',
  '["how many meters in a kilometer", "meters.*kilometer", "kilometer.*meters", "km.*meters"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many meters in a kilometer',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-pints-in-a-quart',
  1,
  'function execute(input) { return "There are 2 pints in 1 quart.\n\nUS liquid volume conversions:\n• 1 quart = 2 pints = 4 cups = 32 fluid ounces\n• 1 gallon = 4 quarts = 8 pints = 16 cups\n• 1 pint = 2 cups = 16 fluid ounces\n• 1 quart ≈ 0.946 liters\n\nThe word \"quart\" comes from \"quarter\" — it''s a quarter of a gallon. Note: US and Imperial (UK) pints differ — a US pint is 473 mL while an Imperial pint is 568 mL."; }',
  '["how many pints in a quart", "pints.*quart", "quart.*pints", "quart.*cup"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many pints in a quart',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-acres-in-a-square-mile',
  1,
  'function execute(input) { return "There are 640 acres in 1 square mile.\n\nLand area conversions:\n• 1 acre = 43,560 square feet ≈ 4,047 square meters\n• 1 acre ≈ 0.405 hectares\n• 1 square mile = 640 acres = 2.59 square kilometers\n• 1 hectare = 2.471 acres\n\nFor reference: a football field (including end zones) is about 1.32 acres. Manhattan is about 14,600 acres (22.8 square miles). An average US single-family lot is about 0.2 acres."; }',
  '["how many acres in a.*mile", "acres.*square mile", "square mile.*acres"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many acres in a square mile',
  'conversion',
  0
),
-- ═══════════════════════════════════════════════════
-- MISCELLANEOUS POPULAR QUESTIONS (12)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-meaning-of-life',
  1,
  'function execute(input) { return "The meaning of life has been debated for millennia with no universal answer. Different perspectives:\n\n• Religious: Fulfill God''s purpose, achieve salvation/enlightenment\n• Existentialist (Sartre): Life has no inherent meaning; you create your own\n• Absurdist (Camus): Embrace life despite its lack of meaning\n• Utilitarian: Maximize happiness and reduce suffering\n• Biological: Survive and reproduce\n• Aristotelian: Achieve eudaimonia (flourishing) through virtue\n• Pop culture: 42 (Douglas Adams, Hitchhiker''s Guide to the Galaxy)\n\nMany philosophers argue that the search itself is what gives life meaning."; }',
  '["meaning of life", "what is the meaning of life", "purpose of life", "why are we here", "what.*point of life"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the meaning of life',
  'philosophy',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-murphy-law',
  1,
  'function execute(input) { return "Murphy''s Law states: \"Anything that can go wrong will go wrong.\" Named after aerospace engineer Edward Murphy, who in 1949 blamed a technician after a rocket sled experiment failed due to every sensor being wired backward. It''s not a scientific law but a practical axiom used in engineering, project management, and everyday life. Related principles include Hofstadter''s Law (\"It always takes longer than you expect, even when you account for Hofstadter''s Law\") and Sod''s Law (British variant, emphasizing that things go wrong at the worst possible time)."; }',
  '["murphy.*law", "what is murphy", "anything that can go wrong", "murphy''s law"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is Murphy''s Law',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-pareto-principle',
  1,
  'function execute(input) { return "The Pareto Principle (80/20 rule) states that roughly 80% of effects come from 20% of causes. Named after economist Vilfredo Pareto, who observed that 80% of Italy''s land was owned by 20% of the population. Common examples:\n\n• 80% of sales come from 20% of customers\n• 80% of bugs come from 20% of the code\n• 80% of results come from 20% of effort\n• 80% of complaints come from 20% of products\n\nIt''s not an exact ratio — the point is that a small number of inputs usually drive the majority of outputs. It''s used in business, productivity, and quality management to prioritize effort."; }',
  '["pareto principle", "80/20 rule", "80 20 rule", "what is the pareto", "pareto.*80.*20"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Pareto Principle',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-pandemic',
  1,
  'function execute(input) { return "A pandemic is an epidemic (outbreak of disease) that has spread across multiple countries or continents, affecting a large number of people. The World Health Organization (WHO) declares pandemics. Key characteristics: wide geographic spread, novelty (population has little immunity), and sustained person-to-person transmission. Notable pandemics: Black Death (1347-1351, ~75-200 million deaths), Spanish Flu (1918-1919, ~50 million), and COVID-19 (2019-present, ~7 million+ confirmed deaths). A pandemic differs from an epidemic (regional) and endemic (constantly present at expected levels, like the common cold)."; }',
  '["what is a pandemic", "pandemic meaning", "pandemic vs epidemic", "define pandemic", "explain pandemic"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a pandemic',
  'health',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-electoral-college',
  1,
  'function execute(input) { return "The Electoral College is the system used to elect the US President. Each state gets electors equal to its total congressional representation (House + Senate). There are 538 total electors; a candidate needs 270 to win. In most states, the winner of the popular vote gets ALL that state''s electors (winner-take-all). This means a candidate can win the presidency while losing the national popular vote (happened in 2000 and 2016). Critics argue it''s undemocratic and gives disproportionate power to swing states. Supporters say it protects smaller states and maintains federalism."; }',
  '["what is the electoral college", "electoral college", "how.*electoral college work", "explain electoral college"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Electoral College',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-photovoltaic',
  1,
  'function execute(input) { return "Photovoltaic (PV) cells, commonly known as solar cells, convert sunlight directly into electricity. The word combines \"photo\" (light) and \"voltaic\" (electricity). They work through the photovoltaic effect: photons from sunlight knock electrons loose from atoms in semiconductor material (usually silicon), creating an electric current. A single cell produces about 0.5 volts; many cells are wired together into solar panels. Modern residential panels are typically 15-22% efficient. Solar energy is the fastest-growing electricity source globally and costs have dropped over 90% since 2010."; }',
  '["what is photovoltaic", "photovoltaic meaning", "how.*solar panel.*work", "how.*solar cell.*work", "solar panel.*explained"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How do solar panels work',
  'technology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-virus-bacteria',
  1,
  'function execute(input) { return "Viruses and bacteria are both microorganisms that can cause disease, but they''re fundamentally different:\n\n• Bacteria are living single-celled organisms that can reproduce on their own. Most are harmless or beneficial (gut bacteria, decomposers). Treated with antibiotics.\n\n• Viruses are NOT alive — they''re genetic material (DNA or RNA) in a protein coat. They can only reproduce by hijacking living cells. Much smaller than bacteria. Cannot be treated with antibiotics; antivirals or vaccines are used.\n\nBacterial infections: strep throat, UTIs, tuberculosis.\nViral infections: flu, COVID-19, common cold, HIV."; }',
  '["virus vs bacteria", "difference.*virus.*bacteria", "bacteria vs virus", "virus.*bacteria.*difference"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Virus vs bacteria',
  'health',
  0
);
