-- WAVE 3 BATCH 5: History, Geography, Programming, More General (55 shards)

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
-- ═══════════════════════════════════════════════════
-- HISTORY (15)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'when-did-ww1-start',
  1,
  'function execute(input) { return "World War I began on July 28, 1914, when Austria-Hungary declared war on Serbia, and ended on November 11, 1918. The immediate trigger was the assassination of Archduke Franz Ferdinand of Austria in Sarajevo on June 28, 1914. Underlying causes included a complex web of alliances, imperial competition, militarism, and nationalism. The war involved the Allied Powers (France, UK, Russia, later US) against the Central Powers (Germany, Austria-Hungary, Ottoman Empire). It resulted in approximately 17 million deaths and reshaped the global political order."; }',
  '["when did ww1 start", "when did world war 1 start", "when.*world war one", "start of ww1", "when did the first world war"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'When did WWI start',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'who-was-cleopatra',
  1,
  'function execute(input) { return "Cleopatra VII (69-30 BC) was the last active ruler of Ptolemaic Egypt. Despite popular belief, she was of Greek-Macedonian descent, not ethnically Egyptian. She was renowned for her intelligence, speaking nine languages, and her political alliances with Roman leaders Julius Caesar and Mark Antony. After Octavian (later Augustus) defeated Antony at the Battle of Actium (31 BC), both Cleopatra and Antony died — she reportedly by snakebite. Her death marked the end of the Ptolemaic dynasty and Egypt became a Roman province."; }',
  '["who was cleopatra", "who is cleopatra", "tell me about cleopatra", "cleopatra.*egypt"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Who was Cleopatra',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'when-was-the-civil-war',
  1,
  'function execute(input) { return "The American Civil War lasted from April 12, 1861 to April 9, 1865. It began when Confederate forces attacked Fort Sumter in South Carolina. The war was fought between the Union (Northern states, led by President Abraham Lincoln) and the Confederacy (11 Southern states that seceded). The central cause was slavery and its expansion into new territories. Approximately 620,000-750,000 soldiers died, making it the deadliest conflict in American history. The Union victory preserved the nation and led to the abolition of slavery (13th Amendment, 1865)."; }',
  '["when was the civil war", "american civil war.*when", "when did the civil war", "civil war.*start", "civil war.*dates"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'When was the American Civil War',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'who-was-julius-caesar',
  1,
  'function execute(input) { return "Gaius Julius Caesar (100-44 BC) was a Roman military general, statesman, and dictator who played a critical role in transforming the Roman Republic into the Roman Empire. He conquered Gaul (modern France), crossed the Rubicon River to start a civil war, and became dictator perpetuo (dictator for life). His reforms included the Julian calendar, land redistribution, and citizenship expansion. He was assassinated on March 15, 44 BC (the Ides of March) by a group of senators including Brutus and Cassius. His adopted heir Octavian became Augustus, the first Roman Emperor."; }',
  '["who was julius caesar", "who is julius caesar", "tell me about.*julius caesar", "caesar.*roman"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Who was Julius Caesar',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-was-the-renaissance',
  1,
  'function execute(input) { return "The Renaissance was a cultural, artistic, and intellectual movement that began in Italy around the 14th century and spread across Europe through the 17th century. The word means \"rebirth\" in French — referring to the revival of classical Greek and Roman knowledge. Key features included humanism (focus on human potential), advances in art (perspective, realism), science (Galileo, Copernicus), literature (Shakespeare, Dante), and exploration. Major figures include Leonardo da Vinci, Michelangelo, Raphael, and Machiavelli. It marked the transition from the Medieval period to the modern age."; }',
  '["what was the renaissance", "the renaissance", "renaissance meaning", "explain.*renaissance", "when was the renaissance"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What was the Renaissance',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-was-the-cold-war',
  1,
  'function execute(input) { return "The Cold War (roughly 1947-1991) was a geopolitical rivalry between the United States and the Soviet Union after World War II. It was \"cold\" because the two superpowers never directly fought each other, but engaged in proxy wars (Korea, Vietnam, Afghanistan), nuclear arms race, space race, espionage, and ideological competition (capitalism vs. communism). Key events include the Berlin Wall (built 1961, fell 1989), Cuban Missile Crisis (1962), and the Moon landing (1969). It ended with the dissolution of the Soviet Union on December 26, 1991."; }',
  '["what was the cold war", "cold war", "cold war meaning", "explain.*cold war", "when was the cold war"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What was the Cold War',
  'history',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'who-was-genghis-khan',
  1,
  'function execute(input) { return "Genghis Khan (c. 1162-1227), born Temüjin, founded the Mongol Empire — the largest contiguous land empire in history. Starting as the leader of a small nomadic tribe, he united the Mongol clans through diplomacy and warfare. His empire eventually stretched from China to Eastern Europe, covering about 24 million square kilometers. He introduced a written Mongol script, established a postal system, promoted religious tolerance, and created a merit-based military. His conquests killed an estimated 40 million people. An estimated 16 million men alive today are his descendants."; }',
  '["who was genghis khan", "who is genghis khan", "tell me about genghis khan", "genghis khan.*mongol"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Who was Genghis Khan',
  'history',
  0
),
-- ═══════════════════════════════════════════════════
-- GEOGRAPHY (15)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-largest-lake',
  1,
  'function execute(input) { return "The largest lake in the world by surface area is the Caspian Sea (despite its name, it''s technically a lake) at 371,000 square kilometers (143,000 sq mi), bordered by Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan. The largest freshwater lake by surface area is Lake Superior (82,100 sq km), one of the Great Lakes. The deepest lake is Lake Baikal in Russia (1,642 meters / 5,387 feet deep), which holds about 20% of the world''s unfrozen freshwater."; }',
  '["largest lake", "biggest lake", "what is the largest lake", "biggest lake.*world", "largest lake.*world"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the largest lake',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-smallest-ocean',
  1,
  'function execute(input) { return "The Arctic Ocean is the smallest and shallowest of the five oceans, covering about 14.06 million square kilometers (5.43 million sq mi). The five oceans from largest to smallest are:\n\n1. Pacific Ocean — 165.25 million km² (largest by far)\n2. Atlantic Ocean — 106.46 million km²\n3. Indian Ocean — 70.56 million km²\n4. Southern (Antarctic) Ocean — 21.96 million km²\n5. Arctic Ocean — 14.06 million km²\n\nThe Arctic Ocean is mostly covered by sea ice, especially in winter."; }',
  '["smallest ocean", "what is the smallest ocean", "five oceans.*size", "oceans.*order.*size", "list.*oceans"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the smallest ocean',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-most-populated-country',
  1,
  'function execute(input) { return "As of 2024, India is the most populated country in the world with approximately 1.44 billion people, having surpassed China in April 2023. The top 10 most populated countries are:\n\n1. India — ~1.44 billion\n2. China — ~1.43 billion\n3. United States — ~340 million\n4. Indonesia — ~277 million\n5. Pakistan — ~240 million\n6. Nigeria — ~224 million\n7. Brazil — ~216 million\n8. Bangladesh — ~173 million\n9. Russia — ~144 million\n10. Ethiopia — ~126 million\n\nTotal world population is approximately 8.1 billion."; }',
  '["most populated country", "most populous country", "largest population", "most people.*country", "which country.*most people"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Most populated country',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-are-the-seven-wonders',
  1,
  'function execute(input) { return "The New Seven Wonders of the World (voted in 2007):\n\n1. Great Wall of China — China\n2. Petra — Jordan\n3. Christ the Redeemer — Brazil\n4. Machu Picchu — Peru\n5. Chichén Itzá — Mexico\n6. Roman Colosseum — Italy\n7. Taj Mahal — India\n\nThe original Seven Wonders of the Ancient World were: Great Pyramid of Giza (only one still standing), Hanging Gardens of Babylon, Statue of Zeus at Olympia, Temple of Artemis at Ephesus, Mausoleum at Halicarnassus, Colossus of Rhodes, and Lighthouse of Alexandria."; }',
  '["seven wonders", "7 wonders", "wonders of the world", "what are the.*wonders", "new seven wonders"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Seven wonders of the world',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-driest-place',
  1,
  'function execute(input) { return "The driest place on Earth is the Atacama Desert in Chile, where some weather stations have never recorded rainfall. The McMurdo Dry Valleys in Antarctica are technically drier — they''ve had virtually no precipitation for about 2 million years, making them the driest place overall. For inhabited locations, Arica, Chile, averages just 0.76mm of rain per year. For context, the Sahara Desert averages about 25mm per year. Death Valley, California, averages about 60mm per year."; }',
  '["driest place", "what is the driest place", "driest.*earth", "driest.*world", "least rain"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the driest place on Earth',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-hottest-place',
  1,
  'function execute(input) { return "The hottest reliably recorded air temperature on Earth was 56.7°C (134°F) in Death Valley, California, on July 10, 1913. However, some meteorologists dispute this record. The highest undisputed temperature is 54.0°C (129.2°F), also in Death Valley, recorded on June 30, 2013. The Lut Desert in Iran has recorded the highest ground surface temperature ever measured by satellite: 70.7°C (159.3°F) in 2005. The hottest consistently inhabited place is Dallol, Ethiopia, with an annual average of 34.6°C (94.3°F)."; }',
  '["hottest place", "what is the hottest place", "hottest.*earth", "hottest.*world", "highest temperature.*recorded"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the hottest place on Earth',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-coldest-place',
  1,
  'function execute(input) { return "The coldest temperature ever recorded on Earth was -89.2°C (-128.6°F) at Vostok Station, Antarctica, on July 21, 1983. Satellite measurements have detected even colder surface temperatures of -98°C (-144.4°F) in small pockets near the East Antarctic ice divide. The coldest permanently inhabited place is Oymyakon, Russia (Siberia), where temperatures have reached -67.7°C (-89.9°F) and the average January temperature is -46°C (-51°F). About 500 people live there year-round."; }',
  '["coldest place", "what is the coldest place", "coldest.*earth", "coldest.*world", "lowest temperature.*recorded"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the coldest place on Earth',
  'geography',
  0
),
-- ═══════════════════════════════════════════════════
-- PROGRAMMING & TECH (18)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-variable',
  1,
  'function execute(input) { return "In programming, a variable is a named container that stores a value in memory. You can think of it as a labeled box that holds data. The value can be changed (it varies — hence \"variable\"). Example in JavaScript: let age = 25; — this creates a variable named \"age\" with the value 25. Variables have a name (identifier), a type (number, string, boolean, etc.), and a value. In some languages you must declare the type (int age = 25 in Java/C), in others it''s inferred (Python, JavaScript)."; }',
  '["what is a variable.*program", "variable in programming", "programming.*variable", "what.*variable.*coding"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a variable in programming',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-function-programming',
  1,
  'function execute(input) { return "In programming, a function is a reusable block of code that performs a specific task. You define it once and call it whenever you need that task done. Functions typically take inputs (parameters/arguments), process them, and return an output. Example in JavaScript:\n\nfunction add(a, b) {\n  return a + b;\n}\nadd(3, 5); // returns 8\n\nBenefits: code reuse (DRY — Don''t Repeat Yourself), modularity, readability, and easier testing. Functions are also called methods (when inside a class), procedures, or subroutines in different contexts."; }',
  '["what is a function.*program", "function in programming", "programming.*function", "what.*function.*coding", "explain.*function.*code"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a function in programming',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-loop',
  1,
  'function execute(input) { return "In programming, a loop is a structure that repeats a block of code multiple times. The main types are:\n\n• for loop — repeats a set number of times: for (let i = 0; i < 5; i++)\n• while loop — repeats as long as a condition is true: while (x > 0)\n• do-while loop — runs at least once, then checks the condition\n• for-each/for-of — iterates over items in a collection\n\nLoops are fundamental for processing lists, repeating calculations, and automating repetitive tasks. An infinite loop (one that never stops) is a common bug — always ensure your loop has a way to end."; }',
  '["what is a loop.*program", "loop in programming", "programming.*loop", "types of loops", "for loop.*while loop"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a loop in programming',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-array',
  1,
  'function execute(input) { return "An array is a data structure that stores an ordered collection of items, accessed by numeric index (position). Arrays start at index 0 in most languages. Example in JavaScript: let fruits = [\"apple\", \"banana\", \"cherry\"]; — fruits[0] is \"apple\", fruits[1] is \"banana\". Arrays can hold any type of data and are one of the most fundamental data structures. Key operations: push (add to end), pop (remove from end), length, sort, filter, and map. In some languages, arrays have a fixed size; in others (like JavaScript and Python), they''re dynamic."; }',
  '["what is an array", "array.*programming", "explain.*array", "array meaning.*code", "what.*array.*coding"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an array in programming',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-recursion',
  1,
  'function execute(input) { return "Recursion is when a function calls itself to solve a problem by breaking it into smaller subproblems. Every recursive function needs: 1) a base case (when to stop), and 2) a recursive case (calling itself with a simpler input). Classic example — factorial:\n\nfunction factorial(n) {\n  if (n <= 1) return 1;     // base case\n  return n * factorial(n-1); // recursive case\n}\nfactorial(5) = 5 × 4 × 3 × 2 × 1 = 120\n\nRecursion is elegant for trees, nested structures, and divide-and-conquer algorithms, but can cause stack overflow if the base case is never reached."; }',
  '["what is recursion", "recursion.*programming", "explain recursion", "recursive function", "recursion meaning"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is recursion',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-database',
  1,
  'function execute(input) { return "A database is an organized collection of structured data stored electronically. It allows you to efficiently store, retrieve, update, and delete data. The two main types are:\n\n• Relational (SQL) — data in tables with rows and columns, linked by relationships. Examples: PostgreSQL, MySQL, SQLite.\n• Non-relational (NoSQL) — flexible formats like documents, key-value pairs, or graphs. Examples: MongoDB, Redis, Neo4j.\n\nDatabases are managed by a DBMS (Database Management System). Nearly every application uses a database — websites, apps, banks, hospitals, and social media all rely on them."; }',
  '["what is a database", "database meaning", "explain.*database", "types of database", "sql vs nosql"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a database',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-json',
  1,
  'function execute(input) { return "JSON (JavaScript Object Notation) is a lightweight data format for storing and exchanging data. It''s human-readable and language-independent, despite its JavaScript origins. JSON uses two structures:\n\n• Objects: key-value pairs in curly braces {\"name\": \"Alice\", \"age\": 30}\n• Arrays: ordered lists in brackets [1, 2, 3]\n\nValues can be strings, numbers, booleans, null, objects, or arrays. JSON is the dominant format for web APIs, configuration files, and data storage. It replaced XML for most use cases because it''s simpler and more compact."; }',
  '["what is json", "json meaning", "explain json", "json format", "what does json stand for"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is JSON',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-ide',
  1,
  'function execute(input) { return "An IDE (Integrated Development Environment) is a software application that provides comprehensive tools for programming in one place. A typical IDE includes:\n\n• Code editor with syntax highlighting\n• Debugger for finding and fixing bugs\n• Compiler/interpreter integration\n• Build automation tools\n• Version control (Git) integration\n\nPopular IDEs: VS Code (most popular, free), IntelliJ IDEA (Java), PyCharm (Python), Xcode (Apple), Android Studio (Android), Visual Studio (Microsoft). The difference between an IDE and a text editor is that IDEs provide integrated tools beyond just writing code."; }',
  '["what is an ide", "ide meaning", "integrated development environment", "best ide", "what does ide stand for"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an IDE',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-open-source',
  1,
  'function execute(input) { return "Open source software is software whose source code is freely available for anyone to view, use, modify, and distribute. Key characteristics: the code is public, anyone can contribute improvements, and it''s usually released under licenses like MIT, Apache, or GPL. Famous open source projects include Linux, Firefox, WordPress, Python, React, and Android. Benefits include transparency, community-driven development, and no licensing costs. It''s different from \"free software\" (which emphasizes freedom over price) and proprietary software (where the code is private)."; }',
  '["what is open source", "open source meaning", "define open source", "explain open source", "open source vs.*proprietary"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is open source',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-boolean',
  1,
  'function execute(input) { return "A boolean is a data type with only two possible values: true or false. Named after mathematician George Boole, who developed Boolean algebra. In programming, booleans are used for conditions and logic:\n\nlet isLoggedIn = true;\nif (isLoggedIn) { showDashboard(); }\n\nComparison operators return booleans: 5 > 3 is true, 2 === 7 is false. In many languages, other values are \"truthy\" or \"falsy\" — for example, 0, empty string, null, and undefined are falsy in JavaScript. Booleans are fundamental to control flow (if/else), loops (while conditions), and logical operations (AND, OR, NOT)."; }',
  '["what is a boolean", "boolean meaning", "boolean.*programming", "explain boolean", "true.*false.*programming"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a boolean',
  'programming',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-css',
  1,
  'function execute(input) { return "CSS (Cascading Style Sheets) is a styling language used to control the visual presentation of HTML documents. While HTML defines the structure and content of a web page, CSS controls how it looks — colors, fonts, spacing, layout, animations, and responsiveness. \"Cascading\" means styles can inherit and override each other based on specificity. CSS can be written inline, in a <style> tag, or in external .css files (preferred). Modern CSS includes Flexbox and Grid for layout, custom properties (variables), media queries for responsive design, and animations."; }',
  '["what is css", "css meaning", "explain css", "what does css stand for", "css.*web"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is CSS',
  'programming',
  0
),
-- ═══════════════════════════════════════════════════
-- MORE GENERAL KNOWLEDGE (5)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-golden-rule',
  1,
  'function execute(input) { return "The Golden Rule is the principle of treating others as you wish to be treated. It appears across virtually every major religion and ethical tradition:\n\n• Christianity: \"Do unto others as you would have them do unto you\" (Matthew 7:12)\n• Islam: \"None of you truly believes until he wishes for his brother what he wishes for himself\"\n• Judaism: \"What is hateful to you, do not do to your neighbor\" (Hillel)\n• Buddhism: \"Hurt not others in ways that you yourself would find hurtful\"\n• Confucianism: \"Do not impose on others what you do not wish for yourself\"\n\nIts near-universality across cultures suggests it may be a fundamental moral intuition."; }',
  '["what is the golden rule", "golden rule", "treat others.*want.*treated", "golden rule.*meaning"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Golden Rule',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-occams-razor',
  1,
  'function execute(input) { return "Occam''s Razor is a problem-solving principle that states: among competing explanations, the simplest one (with the fewest assumptions) is usually correct. Named after William of Ockham, a 14th-century English friar. It doesn''t mean the simplest explanation is always right — just that you shouldn''t multiply assumptions unnecessarily. In science, it guides hypothesis selection. In medicine, doctors are taught \"when you hear hoofbeats, think horses, not zebras.\" It''s a heuristic, not a law — sometimes the complex explanation IS correct."; }',
  '["occam.*razor", "ockham.*razor", "what is occam", "occam''s razor", "explain occam"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is Occam''s Razor',
  'definitions',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-butterfly-effect',
  1,
  'function execute(input) { return "The butterfly effect is the concept that small changes in initial conditions can lead to vastly different outcomes in complex systems. The name comes from the metaphorical idea that a butterfly flapping its wings in Brazil could set off a chain of atmospheric events that eventually causes a tornado in Texas. It was coined by meteorologist Edward Lorenz in the 1960s when he discovered that tiny rounding differences in weather simulations produced wildly different forecasts. It''s a key concept in chaos theory and explains why long-range weather prediction is fundamentally limited."; }',
  '["butterfly effect", "what is the butterfly effect", "explain.*butterfly effect", "butterfly effect meaning"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the butterfly effect',
  'science',
  0
);
