-- WAVE 3 BATCH 2: Finance, Language, Food (50 shards)

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
-- ═══════════════════════════════════════════════════
-- FINANCE & ECONOMICS (20)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-stock',
  1,
  'function execute(input) { return "A stock (or share) represents partial ownership in a company. When you buy stock, you become a shareholder and own a small piece of that company. Stocks are traded on exchanges like the NYSE and NASDAQ. Stock prices fluctuate based on supply, demand, company performance, and market conditions. Investors make money through price appreciation (selling higher than they bought) and dividends (company profit payments to shareholders)."; }',
  '["what is a stock", "what are stocks", "stock meaning", "define stock", "how.*stocks work", "explain stocks"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a stock',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-bond',
  1,
  'function execute(input) { return "A bond is a loan you make to a government or corporation. In return, they pay you interest (the coupon) at regular intervals and return your principal at maturity. Bonds are generally safer than stocks but offer lower returns. Government bonds (like US Treasury bonds) are considered very safe. Corporate bonds pay higher interest but carry more risk. Bond prices move inversely to interest rates — when rates go up, bond prices go down."; }',
  '["what is a bond", "what are bonds", "bond meaning", "define bond", "how.*bonds work", "explain bonds"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a bond',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-mutual-fund',
  1,
  'function execute(input) { return "A mutual fund pools money from many investors to buy a diversified portfolio of stocks, bonds, or other securities. A professional fund manager makes investment decisions. Benefits include diversification (spreading risk), professional management, and accessibility (low minimum investments). Downsides include management fees and less control. Index funds are a type of mutual fund that track a market index like the S&P 500, usually with lower fees."; }',
  '["what is a mutual fund", "mutual fund meaning", "define mutual fund", "how.*mutual fund.*work", "explain mutual fund"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a mutual fund',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-401k',
  1,
  'function execute(input) { return "A 401(k) is a US employer-sponsored retirement savings plan. You contribute pre-tax money from your paycheck, which grows tax-deferred until withdrawal in retirement. Many employers match contributions up to a percentage (free money). The 2024 contribution limit is $23,000 ($30,500 if over 50). Withdrawals before age 59½ typically incur a 10% penalty plus income tax. A Roth 401(k) variant uses after-tax contributions but withdrawals in retirement are tax-free."; }',
  '["what is a 401k", "401k meaning", "define 401k", "how.*401k work", "explain 401k", "what is a 401\\(k\\)"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a 401k',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-etf',
  1,
  'function execute(input) { return "An ETF (Exchange-Traded Fund) is an investment fund that trades on stock exchanges like a regular stock. It typically tracks an index, sector, commodity, or asset class. Unlike mutual funds, ETFs can be bought and sold throughout the trading day at market prices. They usually have lower fees than mutual funds. Popular examples include SPY (tracks S&P 500), QQQ (tracks Nasdaq-100), and VTI (total US stock market)."; }',
  '["what is an etf", "etf meaning", "define etf", "exchange traded fund", "how.*etf.*work", "explain etf"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an ETF',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-interest-rate',
  1,
  'function execute(input) { return "An interest rate is the cost of borrowing money or the reward for saving it, expressed as a percentage. When you take a loan, you pay interest to the lender. When you save, the bank pays you interest. Central banks (like the Federal Reserve) set benchmark rates that influence all other rates. Lower rates encourage borrowing and spending, higher rates encourage saving and slow inflation. The difference between what banks pay savers and charge borrowers is how they profit."; }',
  '["what is.*interest rate", "interest rate meaning", "define interest rate", "how.*interest rate.*work", "explain interest rate"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an interest rate',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-credit-score',
  1,
  'function execute(input) { return "A credit score is a three-digit number (300-850) that represents your creditworthiness — how likely you are to repay borrowed money. Higher is better. The main scoring model is FICO. Factors: payment history (35%), amounts owed (30%), length of credit history (15%), new credit (10%), credit mix (10%). A score above 740 is considered excellent. It affects loan approval, interest rates, apartment rentals, and even some job applications. You can check yours free through many banks and services."; }',
  '["what is.*credit score", "credit score meaning", "how.*credit score.*work", "explain credit score", "what.*good credit score"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a credit score',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-recession',
  1,
  'function execute(input) { return "A recession is a significant decline in economic activity lasting more than a few months. It''s technically defined as two consecutive quarters of declining GDP. Signs include rising unemployment, falling consumer spending, declining business profits, and reduced industrial output. Recessions are a normal part of the economic cycle. The 2008 Great Recession was caused by the housing market crash. Central banks fight recessions by lowering interest rates and governments may increase spending."; }',
  '["what is.*recession", "recession meaning", "define recession", "what causes.*recession", "explain recession"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a recession',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-compound-interest',
  1,
  'function execute(input) { return "Compound interest is interest earned on both the initial principal and previously accumulated interest — essentially \"interest on interest.\" It''s what makes money grow exponentially over time. For example, $1,000 at 10% annual compound interest becomes $1,100 after year one, $1,210 after year two, and $2,594 after 10 years. Albert Einstein reportedly called it the \"eighth wonder of the world.\" The Rule of 72 estimates doubling time: divide 72 by the interest rate."; }',
  '["what is compound interest", "compound interest meaning", "explain compound interest", "how.*compound interest work", "interest on interest"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is compound interest',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-tax-bracket',
  1,
  'function execute(input) { return "Tax brackets are ranges of income taxed at specific rates in a progressive tax system. In the US, higher income is taxed at higher rates, but only the income within each bracket is taxed at that bracket''s rate — not all your income. For example, in 2024 the first $11,600 is taxed at 10%, income from $11,601-$47,150 at 12%, and so on up to 37% for income over $609,350. Your effective (average) tax rate is always lower than your marginal (top bracket) rate."; }',
  '["what is.*tax bracket", "tax bracket meaning", "how.*tax bracket.*work", "explain tax bracket", "marginal tax rate"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a tax bracket',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-mortgage',
  1,
  'function execute(input) { return "A mortgage is a loan used to buy real estate, where the property itself serves as collateral. You make monthly payments of principal (loan amount) and interest over a set term, typically 15 or 30 years. Key terms: down payment (upfront cash, often 3-20%), interest rate (fixed or adjustable), closing costs (fees at purchase), and amortization (how payments are split between principal and interest). If you stop paying, the lender can foreclose and take the property."; }',
  '["what is a mortgage", "mortgage meaning", "define mortgage", "how.*mortgage.*work", "explain mortgage"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a mortgage',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-sp500',
  1,
  'function execute(input) { return "The S&P 500 is a stock market index tracking 500 of the largest US publicly traded companies. It''s widely considered the best single gauge of the US stock market and economy. Companies are weighted by market capitalization (bigger companies have more influence). It includes firms like Apple, Microsoft, Amazon, and Google. The average annual return since inception (1957) is about 10-11%. Many investors use S&P 500 index funds as a core portfolio holding."; }',
  '["what is the s&p 500", "what is the sp500", "s&p 500 meaning", "s&p 500", "sp500", "standard and poor"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the S&P 500',
  'finance',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-federal-reserve',
  1,
  'function execute(input) { return "The Federal Reserve (the Fed) is the central bank of the United States, established in 1913. Its main jobs are setting monetary policy (controlling interest rates and money supply), regulating banks, maintaining financial stability, and providing banking services. The Fed raises interest rates to fight inflation and lowers them to stimulate growth. The Federal Open Market Committee (FOMC) meets eight times a year to set the federal funds rate. The current chair leads the Board of Governors."; }',
  '["what is the federal reserve", "what is the fed", "federal reserve meaning", "explain.*federal reserve", "what does the fed do"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Federal Reserve',
  'finance',
  0
),
-- ═══════════════════════════════════════════════════
-- LANGUAGE & GRAMMAR (15)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-their-there-theyre',
  1,
  'function execute(input) { return "Their, there, and they''re are homophones with different meanings:\n\n• Their = possessive (belonging to them): \"Their house is big.\"\n• There = a place or position: \"The book is over there.\"\n• They''re = contraction of \"they are\": \"They''re coming to dinner.\"\n\nTip: If you can replace it with \"they are,\" use they''re. If it shows possession, use their. Otherwise, use there."; }',
  '["their.*there.*they", "there.*their.*they", "difference.*their.*there", "their vs there", "they''?re vs their"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Their vs there vs they''re',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-your-youre',
  1,
  'function execute(input) { return "Your and you''re are commonly confused:\n\n• Your = possessive (belonging to you): \"Your car is nice.\"\n• You''re = contraction of \"you are\": \"You''re doing great.\"\n\nTip: If you can replace it with \"you are\" and the sentence still makes sense, use you''re. Otherwise, use your."; }',
  '["your vs you''?re", "difference.*your.*you''?re", "your or you''?re", "when to use your"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Your vs you''re',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-affect-effect',
  1,
  'function execute(input) { return "Affect and effect are commonly confused:\n\n• Affect is usually a VERB meaning to influence: \"The weather affects my mood.\"\n• Effect is usually a NOUN meaning a result: \"The effect of the medicine was immediate.\"\n\nMemory trick: Affect = Action (both start with A), Effect = End result (both start with E).\n\nExceptions: \"Effect\" can be a verb meaning to bring about (\"effect change\"), and \"affect\" can be a noun in psychology (emotional expression)."; }',
  '["affect vs effect", "difference.*affect.*effect", "affect or effect", "when to use affect", "when to use effect"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Affect vs effect',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-its-its',
  1,
  'function execute(input) { return "Its and it''s are commonly confused:\n\n• Its = possessive (belonging to it): \"The dog wagged its tail.\"\n• It''s = contraction of \"it is\" or \"it has\": \"It''s raining outside.\"\n\nThis is tricky because we normally use apostrophes for possession (John''s book). But \"its\" is a possessive pronoun like \"his\" or \"hers\" — no apostrophe needed. If you can replace it with \"it is,\" use it''s."; }',
  '["its vs it''s", "difference.*its.*it''s", "its or it''s", "when to use its"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Its vs it''s',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-then-than',
  1,
  'function execute(input) { return "Then and than have different uses:\n\n• Then = relates to time or sequence: \"We ate dinner, then watched a movie.\"\n• Than = used for comparisons: \"She is taller than her brother.\"\n\nTip: ThAN = compArison (both have A). ThEN = whEN (both relate to time, both have E)."; }',
  '["then vs than", "difference.*then.*than", "then or than", "when to use then", "when to use than"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Then vs than',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-pronoun',
  1,
  'function execute(input) { return "A pronoun is a word that replaces a noun to avoid repetition. Types include: personal (I, you, he, she, it, we, they), possessive (my, your, his, her, its, our, their), reflexive (myself, yourself, himself), demonstrative (this, that, these, those), relative (who, which, that), and interrogative (who, what, which). Example: Instead of \"Sarah said Sarah would bring Sarah''s book,\" you say \"Sarah said she would bring her book.\""; }',
  '["what is a pronoun", "pronoun meaning", "types of pronouns", "define pronoun", "explain pronouns"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a pronoun',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-adverb',
  1,
  'function execute(input) { return "An adverb is a word that modifies a verb, adjective, or another adverb. It typically describes how, when, where, or to what extent something happens. Many adverbs end in -ly (quickly, carefully, happily), but not all (very, well, always, never, here, soon). Examples: \"She runs quickly\" (how), \"He arrived yesterday\" (when), \"They looked everywhere\" (where), \"It''s extremely hot\" (to what extent)."; }',
  '["what is an adverb", "adverb meaning", "define adverb", "explain adverb", "adverb examples"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an adverb',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-metaphor',
  1,
  'function execute(input) { return "A metaphor is a figure of speech that directly compares two unlike things by saying one IS the other, without using \"like\" or \"as.\" Examples: \"Time is money,\" \"Life is a journey,\" \"He has a heart of stone.\" Unlike a simile (which uses like/as: \"brave as a lion\"), a metaphor states the comparison directly. Metaphors make language more vivid and help explain abstract concepts through concrete images."; }',
  '["what is a metaphor", "metaphor meaning", "define metaphor", "metaphor examples", "metaphor vs simile"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a metaphor',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-oxymoron',
  1,
  'function execute(input) { return "An oxymoron is a figure of speech that combines two contradictory terms for effect. Examples: \"jumbo shrimp,\" \"deafening silence,\" \"bittersweet,\" \"living dead,\" \"pretty ugly,\" \"act naturally,\" \"clearly confused,\" and \"open secret.\" The word itself is an oxymoron — from Greek oxys (sharp) and moros (dull). Oxymorons create a dramatic effect, add humor, or express complex emotions that seem contradictory."; }',
  '["what is an oxymoron", "oxymoron meaning", "define oxymoron", "oxymoron examples", "examples of oxymoron"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an oxymoron',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-an-acronym',
  1,
  'function execute(input) { return "An acronym is a word formed from the first letters of a phrase, pronounced as a word. Examples: NASA (National Aeronautics and Space Administration), SCUBA (Self-Contained Underwater Breathing Apparatus), and LASER (Light Amplification by Stimulated Emission of Radiation). An initialism is similar but each letter is said individually: FBI, HTML, CEO. Some acronyms become so common people forget they''re acronyms, like radar and zip code."; }',
  '["what is an acronym", "acronym meaning", "define acronym", "acronym examples", "acronym vs initialism"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is an acronym',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-alliteration',
  1,
  'function execute(input) { return "Alliteration is the repetition of the same beginning consonant sound in a series of words close together. Examples: \"Peter Piper picked a peck of pickled peppers,\" \"She sells seashells by the seashore,\" and \"Big bad wolf.\" It''s used in poetry, rhetoric, branding (Coca-Cola, Best Buy, Dunkin'' Donuts), and tongue twisters. It creates rhythm, makes phrases memorable, and adds musical quality to language."; }',
  '["what is alliteration", "alliteration meaning", "define alliteration", "alliteration examples", "examples of alliteration"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is alliteration',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'difference-who-whom',
  1,
  'function execute(input) { return "Who vs whom:\n\n• Who = subject (does the action): \"Who is calling?\"\n• Whom = object (receives the action): \"To whom should I address this?\"\n\nSimple trick: If you can replace it with \"he/she,\" use who. If you can replace it with \"him/her,\" use whom. \"Who called?\" → \"He called\" ✓. \"Whom did you call?\" → \"You called him\" ✓. In casual speech, \"who\" is often used for both, and \"whom\" is becoming less common."; }',
  '["who vs whom", "difference.*who.*whom", "who or whom", "when to use whom", "when to use who"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Who vs whom',
  'language',
  0
),
-- ═══════════════════════════════════════════════════
-- FOOD & COOKING (15)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'cups-in-a-gallon',
  1,
  'function execute(input) { return "There are 16 cups in a gallon. Here''s the breakdown:\n\n• 1 gallon = 4 quarts\n• 1 quart = 2 pints\n• 1 pint = 2 cups\n• So: 4 × 2 × 2 = 16 cups\n\nOther useful conversions: 1 gallon = 128 fluid ounces, 1 cup = 8 fluid ounces, 1 gallon ≈ 3.785 liters."; }',
  '["how many cups in a gallon", "cups.*gallon", "gallon.*cups", "cups per gallon"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many cups in a gallon',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'tablespoons-in-a-cup',
  1,
  'function execute(input) { return "There are 16 tablespoons in 1 cup. Other useful conversions:\n\n• 1 tablespoon = 3 teaspoons\n• 1 cup = 48 teaspoons\n• 1 cup = 8 fluid ounces\n• ½ cup = 8 tablespoons\n• ¼ cup = 4 tablespoons\n• ⅓ cup = 5 tablespoons + 1 teaspoon"; }',
  '["how many tablespoons in a cup", "tablespoons.*cup", "cup.*tablespoons", "tbsp.*cup"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many tablespoons in a cup',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'ounces-in-a-pound',
  1,
  'function execute(input) { return "There are 16 ounces in 1 pound. Quick reference:\n\n• 1 pound = 16 ounces = 453.6 grams\n• ½ pound = 8 ounces = 226.8 grams\n• ¼ pound = 4 ounces = 113.4 grams\n• 1 ounce = 28.35 grams\n\nNote: These are avoirdupois ounces (weight). Fluid ounces measure volume, not weight — they''re different measurements."; }',
  '["how many ounces in a pound", "ounces.*pound", "pound.*ounces", "oz.*pound", "oz in a lb"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many ounces in a pound',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'boiling-point-of-water-fahrenheit',
  1,
  'function execute(input) { return "Water boils at 212°F (100°C) at standard atmospheric pressure (sea level). At higher altitudes, the boiling point decreases because air pressure is lower. For example, in Denver (5,280 ft elevation), water boils at about 202°F. This is why high-altitude cooking often requires adjustments — food takes longer to cook because the water is boiling at a lower temperature."; }',
  '["what temp.*water boil.*fahrenheit", "boiling point.*fahrenheit", "water boil.*degrees"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Boiling point of water in Fahrenheit',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-teaspoons-tablespoon',
  1,
  'function execute(input) { return "There are 3 teaspoons in 1 tablespoon. Quick reference:\n\n• 1 tablespoon = 3 teaspoons = 15 mL\n• 1 teaspoon = 5 mL\n• ½ tablespoon = 1½ teaspoons\n• 1 dessert spoon = 2 teaspoons (used in some countries)"; }',
  '["how many teaspoons in a tablespoon", "teaspoons.*tablespoon", "tsp.*tbsp", "tablespoon.*teaspoons"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many teaspoons in a tablespoon',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-gluten',
  1,
  'function execute(input) { return "Gluten is a group of proteins found in wheat, barley, rye, and their derivatives. It gives dough its elastic, stretchy texture and helps bread rise and keep its shape. Most people digest gluten without issues. However, people with celiac disease (about 1% of the population) have an autoimmune reaction to gluten that damages the small intestine. Non-celiac gluten sensitivity causes discomfort without intestinal damage. Gluten-free alternatives include rice, corn, quinoa, and oats (if not cross-contaminated)."; }',
  '["what is gluten", "gluten meaning", "define gluten", "explain gluten", "what does gluten do"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is gluten',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-difference-baking-soda-powder',
  1,
  'function execute(input) { return "Baking soda and baking powder are both leavening agents (they make baked goods rise), but they work differently:\n\n• Baking soda (sodium bicarbonate) needs an ACID to activate (buttermilk, lemon juice, vinegar). It reacts immediately when wet.\n\n• Baking powder contains baking soda PLUS a built-in acid. It''s \"double-acting\" — reacts once when wet and again when heated.\n\nYou can''t always substitute one for the other. Using baking soda without acid leaves a metallic taste. Using baking powder when a recipe needs soda may not rise enough."; }',
  '["baking soda vs.*powder", "difference.*baking soda.*powder", "baking powder vs.*soda", "baking soda or.*powder"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Baking soda vs baking powder',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-umami',
  1,
  'function execute(input) { return "Umami is the fifth basic taste, alongside sweet, sour, salty, and bitter. The Japanese word means \"pleasant savory taste.\" It was identified by chemist Kikunae Ikeda in 1908. Umami comes from glutamate, an amino acid found naturally in many foods: parmesan cheese, soy sauce, mushrooms, tomatoes, miso, seaweed, anchovies, and aged meats. MSG (monosodium glutamate) is a concentrated form. Umami adds depth and savoriness to food and makes dishes taste more satisfying."; }',
  '["what is umami", "umami meaning", "umami taste", "define umami", "fifth taste"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is umami',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'safe-internal-temperature-chicken',
  1,
  'function execute(input) { return "The safe internal temperature for chicken is 165°F (74°C) as recommended by the USDA. This applies to all parts of the chicken — breast, thigh, wing, and ground chicken. Use a meat thermometer inserted into the thickest part, avoiding bone. At 165°F, harmful bacteria like Salmonella are killed instantly. Resting the chicken for a few minutes after cooking allows carryover cooking and juices to redistribute."; }',
  '["chicken.*temperature", "what temp.*chicken", "safe.*temp.*chicken", "internal temp.*chicken", "how.*hot.*cook chicken"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Safe cooking temperature for chicken',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-calories-in-a-banana',
  1,
  'function execute(input) { return "A medium banana (about 7 inches) has approximately 105 calories. Nutritional breakdown:\n\n• Carbohydrates: 27g (14g sugar, 3g fiber)\n• Protein: 1.3g\n• Fat: 0.4g\n• Potassium: 422mg (12% daily value)\n• Vitamin B6: 25% daily value\n• Vitamin C: 17% daily value\n\nBananas are a good source of quick energy, potassium (important for heart and muscle function), and dietary fiber."; }',
  '["how many calories.*banana", "calories in.*banana", "banana.*calories", "banana nutrition"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Calories in a banana',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-calories-in-an-egg',
  1,
  'function execute(input) { return "A large egg has about 70-78 calories. Nutritional breakdown:\n\n• Protein: 6g (mostly in the white)\n• Fat: 5g (mostly in the yolk)\n• Cholesterol: 186mg (all in the yolk)\n• Carbohydrates: less than 1g\n• Vitamin D: 6% daily value\n• Vitamin B12: 15% daily value\n\nPreparation matters: a boiled or poached egg stays at ~70 calories, but frying in butter adds ~30-50 more. Eggs are one of the most nutrient-dense foods available."; }',
  '["how many calories.*egg", "calories in.*egg", "egg.*calories", "egg nutrition"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Calories in an egg',
  'food',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'grams-in-an-ounce',
  1,
  'function execute(input) { return "There are approximately 28.35 grams in 1 ounce. Quick reference:\n\n• 1 oz = 28.35 g\n• 2 oz = 56.7 g\n• 4 oz (¼ lb) = 113.4 g\n• 8 oz (½ lb) = 226.8 g\n• 16 oz (1 lb) = 453.6 g\n\nFor rough mental math, 1 oz ≈ 28 grams. This is for weight (avoirdupois) ounces. Troy ounces (used for precious metals) are slightly heavier at 31.1 grams."; }',
  '["how many grams in an ounce", "grams.*ounce", "ounce.*grams", "oz to grams", "grams per ounce"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many grams in an ounce',
  'food',
  0
);
