-- WAVE 3 BATCH 4: Nature, Psychology, Everyday Knowledge (50 shards)

INSERT INTO procedural_shards (id, name, version, logic, patterns, knowledge_type, visibility, lifecycle, confidence, synthesis_method, synthesis_confidence, description, category, estimated_tokens)
VALUES
-- ═══════════════════════════════════════════════════
-- NATURE & ENVIRONMENT (18)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'why-do-seasons-change',
  1,
  'function execute(input) { return "Seasons change because Earth''s axis is tilted 23.5 degrees relative to its orbit around the Sun. This tilt means different parts of Earth receive different amounts of direct sunlight throughout the year. When the Northern Hemisphere tilts toward the Sun, it''s summer there (and winter in the Southern Hemisphere). Six months later, the situation reverses. It''s NOT because of Earth''s distance from the Sun — in fact, Earth is closest to the Sun in January (Northern Hemisphere winter). The equator experiences minimal seasonal change."; }',
  '["why do seasons change", "what causes seasons", "why.*we have seasons", "how do seasons work", "earth.*tilt.*seasons"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Why do seasons change',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'why-is-the-ocean-salty',
  1,
  'function execute(input) { return "The ocean is salty because rivers carry dissolved minerals (including sodium and chloride) from rocks and soil into the sea. Over billions of years, these salts have accumulated. Underwater volcanic vents also release minerals. The ocean doesn''t get saltier over time because salt is also removed — organisms use it, and it gets deposited as sediment. Ocean water is about 3.5% salt by weight. The Dead Sea is about 34% salt (nearly 10x saltier). Rain and rivers are fresh because evaporation leaves salt behind."; }',
  '["why is the ocean salty", "why.*sea.*salty", "what makes.*ocean salty", "where.*ocean salt come from"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Why is the ocean salty',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-do-rainbows-form',
  1,
  'function execute(input) { return "Rainbows form when sunlight enters water droplets in the air, refracts (bends), reflects off the back of the droplet, and refracts again as it exits. This process separates white light into its component colors because each wavelength bends at a slightly different angle. The order is always: red (outside), orange, yellow, green, blue, indigo, violet (inside) — remembered by ROY G. BIV. You need the sun behind you and rain in front of you. Double rainbows occur when light reflects twice inside the droplet, reversing the color order in the outer bow."; }',
  '["how.*rainbow.*form", "what causes.*rainbow", "why.*rainbow", "how.*rainbows.*made", "rainbow.*explained"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How do rainbows form',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-causes-thunder',
  1,
  'function execute(input) { return "Thunder is caused by lightning. When lightning strikes, it superheats the air to about 30,000°C (54,000°F) — five times hotter than the Sun''s surface. This rapid heating causes the air to expand explosively, creating a shockwave that we hear as thunder. The rumbling sound occurs because sound from different parts of the lightning bolt reaches your ears at different times. You can estimate your distance from lightning: count seconds between flash and thunder, then divide by 5 for miles (or 3 for kilometers)."; }',
  '["what causes thunder", "why does it thunder", "how.*thunder.*made", "thunder.*explained", "what makes thunder"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What causes thunder',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-greenhouse-effect',
  1,
  'function execute(input) { return "The greenhouse effect is the process where certain gases in Earth''s atmosphere trap heat from the Sun, warming the planet. Sunlight passes through the atmosphere, warms Earth''s surface, which then radiates heat (infrared radiation) back up. Greenhouse gases (CO2, methane, water vapor, nitrous oxide) absorb this heat and re-emit it in all directions, including back toward Earth. Without this natural effect, Earth would average -18°C (0°F) instead of 15°C (59°F). The problem is human activities are increasing greenhouse gases, enhancing the effect and causing global warming."; }',
  '["what is the greenhouse effect", "greenhouse effect", "explain.*greenhouse effect", "how.*greenhouse effect work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the greenhouse effect',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-ozone-layer',
  1,
  'function execute(input) { return "The ozone layer is a region of Earth''s stratosphere (15-35 km altitude) with a high concentration of ozone (O3) molecules. It absorbs 97-99% of the Sun''s harmful ultraviolet (UV) radiation, protecting life on Earth from DNA damage, skin cancer, and cataracts. In the 1980s, scientists discovered a \"hole\" over Antarctica caused by chemicals called CFCs (chlorofluorocarbons) used in refrigerants and aerosols. The 1987 Montreal Protocol banned CFCs, and the ozone layer has been slowly recovering since — one of the most successful environmental agreements in history."; }',
  '["what is the ozone layer", "ozone layer", "explain.*ozone", "ozone hole", "what does.*ozone.*do"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the ozone layer',
  'science',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-old-is-a-tree-rings',
  1,
  'function execute(input) { return "You can determine a tree''s age by counting its growth rings. Each ring represents one year of growth. The ring has two parts: a lighter section (spring/summer growth, when the tree grows quickly) and a darker section (fall/winter, slower growth). Wide rings indicate good growing conditions (plenty of rain); narrow rings indicate stress (drought, cold). This science is called dendrochronology. The oldest known tree is a bristlecone pine in California named Methuselah, over 4,850 years old. Some clonal colonies are much older."; }',
  '["how.*tell.*tree.*age", "tree rings", "how old.*tree", "tree.*age.*rings", "dendrochronology"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How to tell a tree''s age',
  'nature',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'why-do-cats-purr',
  1,
  'function execute(input) { return "Cats purr by rapidly vibrating the muscles in their larynx (voice box), creating sound at 25-150 Hz as they breathe in and out. Cats purr when happy, but also when stressed, injured, or sick — suggesting purring serves multiple purposes. The vibration frequency may promote bone healing and tissue repair. Cats purr to communicate with their owners (solicitation purring sounds more urgent), to self-soothe when anxious, and mother cats purr to bond with kittens. Not all cats can purr — big cats that roar (lions, tigers) generally can''t purr, and vice versa."; }',
  '["why do cats purr", "cat purr", "why.*cats.*purr", "how.*cats purr", "what does.*purring mean"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Why do cats purr',
  'animals',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'why-do-dogs-wag-their-tails',
  1,
  'function execute(input) { return "Dogs wag their tails to communicate emotions, but it doesn''t always mean happiness. Right-biased wagging indicates positive emotions (seeing their owner). Left-biased wagging indicates negative emotions (seeing an unfamiliar dominant dog). A high, fast wag usually means excitement or arousal. A slow wag at half-mast can mean insecurity. A tucked tail signals fear. A stiff, high tail with small fast wags can signal aggression. Dogs don''t wag when alone — it''s specifically a social communication tool, much like humans smiling."; }',
  '["why do dogs wag.*tail", "dog.*wag.*tail", "what does.*tail wag.*mean", "why.*dogs.*wag"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Why do dogs wag their tails',
  'animals',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-do-bees-make-honey',
  1,
  'function execute(input) { return "Bees make honey through a multi-step process: 1) Forager bees collect nectar from flowers using their long tongues, storing it in a special \"honey stomach.\" 2) Back at the hive, they pass the nectar mouth-to-mouth to processor bees. 3) Enzymes in the bees'' stomachs break down complex sugars into simple sugars. 4) Bees spread the nectar into honeycomb cells and fan it with their wings to evaporate water content from ~70% down to ~18%. 5) They cap the cells with beeswax. A single bee produces only about 1/12 teaspoon of honey in its lifetime. One pound of honey represents about 2 million flower visits."; }',
  '["how do bees make honey", "how.*honey.*made", "bees.*make.*honey", "honey production"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How do bees make honey',
  'animals',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-water-cycle',
  1,
  'function execute(input) { return "The water cycle (hydrological cycle) is the continuous movement of water through Earth''s systems. The main stages are: 1) Evaporation — sun heats water in oceans, lakes, and rivers, turning it to vapor. 2) Transpiration — plants release water vapor through their leaves. 3) Condensation — water vapor cools and forms clouds. 4) Precipitation — water falls as rain, snow, sleet, or hail. 5) Collection — water flows into rivers, lakes, and oceans, or seeps into groundwater. The total amount of water on Earth stays roughly constant — the same water has been cycling for billions of years."; }',
  '["what is the water cycle", "water cycle", "explain.*water cycle", "how.*water cycle work", "stages.*water cycle"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the water cycle',
  'science',
  0
),
-- ═══════════════════════════════════════════════════
-- PSYCHOLOGY & BEHAVIOR (10)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-introvert-vs-extrovert',
  1,
  'function execute(input) { return "Introverts and extroverts differ primarily in how they recharge energy:\n\n• Introverts recharge through alone time. They prefer deep one-on-one conversations, think before speaking, and can feel drained by large social gatherings. They''re not necessarily shy — they simply need solitude to process.\n\n• Extroverts recharge through social interaction. They think out loud, enjoy group activities, and feel energized by being around people.\n\nMost people are ambiverts — somewhere in between. The concept was popularized by Carl Jung. It''s a spectrum, not a binary."; }',
  '["introvert vs extrovert", "difference.*introvert.*extrovert", "what is.*introvert", "what is.*extrovert", "introvert.*extrovert"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Introvert vs extrovert',
  'psychology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-imposter-syndrome',
  1,
  'function execute(input) { return "Imposter syndrome is the persistent feeling that you''re a fraud who doesn''t deserve your success, despite evidence of competence. People with imposter syndrome attribute their achievements to luck, timing, or deceiving others rather than their own ability. It was first described by psychologists Pauline Clance and Suzanne Imes in 1978. An estimated 70% of people experience it at some point. It''s common among high achievers, people entering new roles, and those from underrepresented groups. It''s not a clinical diagnosis but a widespread psychological pattern."; }',
  '["what is imposter syndrome", "impostor syndrome", "imposter syndrome meaning", "explain imposter syndrome", "do i have imposter syndrome"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is imposter syndrome',
  'psychology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-confirmation-bias',
  1,
  'function execute(input) { return "Confirmation bias is the tendency to search for, interpret, and remember information that confirms your existing beliefs, while ignoring or dismissing contradictory evidence. For example, if you believe a new diet works, you''ll notice every positive result and overlook when it doesn''t help. It affects everyone regardless of intelligence. It''s amplified by social media algorithms that show you content matching your views. To counter it: actively seek opposing viewpoints, consider you might be wrong, and evaluate evidence objectively."; }',
  '["what is confirmation bias", "confirmation bias", "explain confirmation bias", "define confirmation bias"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is confirmation bias',
  'psychology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-dunning-kruger-effect',
  1,
  'function execute(input) { return "The Dunning-Kruger effect is a cognitive bias where people with limited knowledge in a domain overestimate their competence, while experts tend to underestimate theirs. Named after psychologists David Dunning and Justin Kruger (1999). The key insight: incompetent people lack the skill to recognize their own incompetence. As someone gains real expertise, they become more aware of how much they don''t know, leading to lower self-assessment. It''s often summarized as: beginners don''t know what they don''t know."; }',
  '["dunning.?kruger", "what is.*dunning.?kruger", "dunning.?kruger effect", "explain dunning.?kruger"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the Dunning-Kruger effect',
  'psychology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-maslow-hierarchy',
  1,
  'function execute(input) { return "Maslow''s hierarchy of needs is a psychological theory (Abraham Maslow, 1943) that arranges human needs in a pyramid with five levels:\n\n1. Physiological — food, water, shelter, sleep\n2. Safety — security, employment, health\n3. Love/belonging — friendship, family, intimacy\n4. Esteem — respect, recognition, confidence\n5. Self-actualization — creativity, purpose, reaching full potential\n\nThe theory suggests lower needs must be largely met before higher ones become motivating. While influential, it''s been criticized for being too rigid and Western-centric — people can pursue higher needs even when lower ones aren''t fully met."; }',
  '["maslow.*hierarchy", "hierarchy of needs", "maslow''s.*needs", "what is maslow", "maslow.*pyramid"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Maslow''s hierarchy of needs',
  'psychology',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-anchoring-bias',
  1,
  'function execute(input) { return "Anchoring bias is the tendency to rely too heavily on the first piece of information you encounter (the \"anchor\") when making decisions. For example, if a shirt is marked \"Was $100, now $40,\" the $100 anchor makes $40 seem like a deal — even if the shirt is only worth $25. Anchoring affects negotiations (the first number sets the range), salary discussions, pricing, and even sentencing in court. To counter it: be aware of initial numbers, consider the decision independently, and generate your own estimates before seeing others''."; }',
  '["what is anchoring bias", "anchoring bias", "anchoring effect", "explain anchoring bias", "define anchoring"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is anchoring bias',
  'psychology',
  0
),
-- ═══════════════════════════════════════════════════
-- EVERYDAY KNOWLEDGE (22)
-- ═══════════════════════════════════════════════════
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-feet-in-a-mile',
  1,
  'function execute(input) { return "There are 5,280 feet in a mile. Other useful conversions:\n\n• 1 mile = 5,280 feet = 1,760 yards = 1.609 kilometers\n• 1 kilometer = 0.621 miles = 3,281 feet\n• 1 nautical mile = 1.151 regular miles = 6,076 feet\n\nThe word \"mile\" comes from the Latin \"mille passus\" meaning \"a thousand paces\" — the Roman mile was 5,000 feet. The modern mile was standardized at 5,280 feet in 1593 by English statute."; }',
  '["how many feet in a mile", "feet.*mile", "mile.*feet", "ft in a mile"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many feet in a mile',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-inches-in-a-foot',
  1,
  'function execute(input) { return "There are 12 inches in 1 foot. Other useful conversions:\n\n• 1 foot = 12 inches = 30.48 centimeters\n• 1 inch = 2.54 centimeters\n• 1 yard = 3 feet = 36 inches\n• 1 meter = 3.281 feet = 39.37 inches\n\nThe foot measurement originally varied by region but was standardized internationally in 1959. The inch was originally defined as the width of a man''s thumb."; }',
  '["how many inches in a foot", "inches.*foot", "foot.*inches", "in.*ft"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many inches in a foot',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-yards-in-a-mile',
  1,
  'function execute(input) { return "There are 1,760 yards in a mile.\n\n• 1 mile = 1,760 yards = 5,280 feet\n• 1 yard = 3 feet = 0.9144 meters\n• 1 mile = 1,609.34 meters ≈ 1.6 kilometers\n\nQuick mental math: to convert miles to yards, multiply by 1,760. To convert yards to miles, divide by 1,760."; }',
  '["how many yards in a mile", "yards.*mile", "mile.*yards"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many yards in a mile',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-days-in-each-month',
  1,
  'function execute(input) { return "Days in each month:\n\n• January: 31\n• February: 28 (29 in leap years)\n• March: 31\n• April: 30\n• May: 31\n• June: 30\n• July: 31\n• August: 31\n• September: 30\n• October: 31\n• November: 30\n• December: 31\n\nMemory trick (knuckle method): Make fists and count across your knuckles. Knuckle = 31 days, valley = 30 days (except February). Or use the rhyme: \"Thirty days hath September, April, June, and November...\""; }',
  '["how many days.*month", "days in each month", "days.*february", "days.*month", "30 days.*month"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many days in each month',
  'datetime',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-weeks-in-a-year',
  1,
  'function execute(input) { return "There are 52 weeks in a year, plus 1 extra day (2 extra in a leap year). Technically, a common year has 52 weeks and 1 day (365 ÷ 7 = 52.143). A leap year has 52 weeks and 2 days. This is why dates shift by one day of the week each year (or two days after a leap year). Some fiscal and accounting calendars use exactly 52 weeks (364 days) for consistency."; }',
  '["how many weeks in a year", "weeks.*year", "year.*weeks"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many weeks in a year',
  'datetime',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-seconds-in-a-day',
  1,
  'function execute(input) { return "There are 86,400 seconds in a day.\n\nBreakdown: 24 hours × 60 minutes × 60 seconds = 86,400.\n\nOther time conversions:\n• 1 hour = 3,600 seconds\n• 1 day = 1,440 minutes = 86,400 seconds\n• 1 week = 604,800 seconds\n• 1 year ≈ 31,536,000 seconds (31,622,400 in a leap year)"; }',
  '["how many seconds in a day", "seconds.*day", "day.*seconds"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many seconds in a day',
  'datetime',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-minutes-in-a-year',
  1,
  'function execute(input) { return "There are 525,600 minutes in a standard year (365 days). In a leap year (366 days), there are 527,040 minutes.\n\nCalculation: 365 days × 24 hours × 60 minutes = 525,600.\n\nThis number was famously popularized by the song \"Seasons of Love\" from the musical Rent: \"Five hundred twenty-five thousand six hundred minutes...\""; }',
  '["how many minutes in a year", "minutes.*year", "year.*minutes", "525600"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many minutes in a year',
  'datetime',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-a-leap-year',
  1,
  'function execute(input) { return "A leap year has 366 days instead of 365, with February having 29 days instead of 28. It occurs every 4 years to account for the fact that Earth takes approximately 365.25 days to orbit the Sun. The rules: a year is a leap year if divisible by 4, EXCEPT years divisible by 100 are NOT leap years, UNLESS also divisible by 400. So 2000 was a leap year (÷400), 1900 was not (÷100 but not ÷400), and 2024 was (÷4). The next leap years are 2028, 2032, and 2036."; }',
  '["what is a leap year", "leap year.*rules", "when is.*leap year", "why.*leap year", "how.*leap year work"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is a leap year',
  'datetime',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-tallest-building',
  1,
  'function execute(input) { return "The tallest building in the world is the Burj Khalifa in Dubai, UAE, standing at 828 meters (2,717 feet) with 163 floors. It was completed in 2010. The next tallest buildings are Merdeka 118 in Kuala Lumpur (678m), Shanghai Tower (632m), Abraj Al-Bait Clock Tower in Mecca (601m), and Ping An Finance Centre in Shenzhen (599m). The Jeddah Tower in Saudi Arabia, if completed, would surpass the Burj Khalifa at over 1,000 meters."; }',
  '["tallest building", "what is the tallest building", "highest building", "tallest.*building.*world", "burj khalifa.*height"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'What is the tallest building',
  'geography',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-longest-word-english',
  1,
  'function execute(input) { return "The longest word in common English dictionaries is \"pneumonoultramicroscopicsilicovolcanoconiosis\" (45 letters) — a lung disease caused by inhaling fine silica dust. However, this word was coined specifically to be long. More practical long words include \"antidisestablishmentarianism\" (28 letters, opposition to separating church and state) and \"floccinaucinihilipilification\" (29 letters, estimating something as worthless). The longest commonly used English word is arguably \"uncharacteristically\" (20 letters)."; }',
  '["longest word.*english", "what is the longest word", "longest english word", "biggest word"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Longest word in English',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-most-spoken-language',
  1,
  'function execute(input) { return "By total speakers (native + second language), the most spoken languages are:\n\n1. English — ~1.5 billion speakers\n2. Mandarin Chinese — ~1.1 billion\n3. Hindi — ~600 million\n4. Spanish — ~560 million\n5. Arabic — ~310 million\n6. French — ~310 million\n7. Bengali — ~270 million\n8. Portuguese — ~260 million\n\nBy NATIVE speakers only, Mandarin leads (~920 million), followed by Spanish (~475 million), then English (~380 million). There are roughly 7,000 languages spoken worldwide, with about half expected to disappear by 2100."; }',
  '["most spoken language", "most popular language", "most common language", "most.*spoken.*language.*world"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Most spoken language in the world',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-letters-in-alphabet',
  1,
  'function execute(input) { return "The English alphabet has 26 letters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z. There are 21 consonants and 5 vowels (A, E, I, O, U). The letter Y is sometimes considered a vowel when it makes a vowel sound (as in \"gym\" or \"happy\"). The most common letters in English are E, T, A, O, I, N, S, H, R. The least common are Z, Q, X, J."; }',
  '["how many letters.*alphabet", "letters in.*alphabet", "alphabet.*how many", "english alphabet.*letters"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many letters in the alphabet',
  'language',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'what-is-the-speed-limit-on-highways',
  1,
  'function execute(input) { return "In the US, highway speed limits vary by state. The most common interstate speed limit is 70 mph (113 km/h). Some western states allow 75-80 mph, and parts of Texas have an 85 mph limit (the highest in the nation). Urban interstates are typically 55-65 mph. School zones are usually 15-25 mph. In Europe, most countries use 120-130 km/h (75-81 mph) on motorways. Germany''s Autobahn has no general speed limit on many sections, though 130 km/h is recommended."; }',
  '["speed limit.*highway", "highway speed limit", "how fast.*highway", "speed limit.*interstate", "fastest speed limit"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'Highway speed limits',
  'general',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-much-does-a-gallon-of-water-weigh',
  1,
  'function execute(input) { return "A US gallon of water weighs approximately 8.34 pounds (3.785 kilograms) at room temperature. An Imperial (UK) gallon weighs about 10.02 pounds (4.546 kg). The exact weight varies slightly with temperature — cold water is denser and slightly heavier. The old saying \"a pint''s a pound the world around\" is only approximate — a US pint of water actually weighs about 1.04 pounds. One liter of water weighs almost exactly 1 kilogram (2.2 pounds)."; }',
  '["how much.*gallon.*water weigh", "weight.*gallon.*water", "gallon of water.*pounds", "how heavy.*gallon.*water"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How much does a gallon of water weigh',
  'general',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-liters-in-a-gallon',
  1,
  'function execute(input) { return "There are approximately 3.785 liters in a US gallon. Quick reference:\n\n• 1 US gallon = 3.785 liters\n• 1 Imperial (UK) gallon = 4.546 liters\n• 1 liter = 0.264 US gallons\n• 1 liter = 33.81 US fluid ounces\n\nThe US and Imperial gallons are different sizes. The US gallon is based on the wine gallon (231 cubic inches), while the Imperial gallon is based on the volume of 10 pounds of water (277.4 cubic inches)."; }',
  '["how many liters in a gallon", "liters.*gallon", "gallon.*liters", "gallons to liters"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many liters in a gallon',
  'conversion',
  0
),
(
  'shd_w3_' || substr(md5(random()::text), 1, 20),
  'how-many-centimeters-in-a-meter',
  1,
  'function execute(input) { return "There are 100 centimeters in 1 meter. The metric system is based on powers of 10:\n\n• 1 meter = 100 centimeters = 1,000 millimeters\n• 1 meter = 3.281 feet = 39.37 inches\n• 1 centimeter = 10 millimeters = 0.394 inches\n• 1 kilometer = 1,000 meters\n\nThe prefix \"centi-\" means one-hundredth, so a centimeter is literally 1/100th of a meter. Similarly, \"milli-\" means one-thousandth and \"kilo-\" means one thousand."; }',
  '["how many centimeters in a meter", "cm.*meter", "meter.*cm", "centimeters.*meter"]',
  'immutable',
  'public',
  'promoted',
  0.95,
  'manual',
  0.95,
  'How many centimeters in a meter',
  'conversion',
  0
);
